// AUTO-GENERATED by scripts/import-ufi-parts.py — do not edit by hand.
// Source: docs/export/2024.11.14 Cotação Turbo Diesel UFI.xlsx (aba "Cotação Turbo Diesel").
import type { IUfiPartRow } from "../generators/ufiPart";

export const UFI_PARTS_RAW: IUfiPartRow[] = [];
