/**
 * Resolves the quoted message of an inbound/echo event into the snapshot
 * persisted in `messages.reply_to`.
 *
 * Edge-runtime module (Deno, service_role): NOT part of the
 * src/providers/whatsapp mirror — that tree is wiped and regenerated by the
 * sync script. The PURE part of the reconciliation lives in the mirrored
 * `whatsapp/waha/replyRef.ts`, so front and Edge share one implementation.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.107.0";
import { pickReplyMatch, truncateQuotedText } from "./whatsapp/waha/replyRef.ts";
import { MEDIA_DISCRIMINATOR_TYPES } from "./whatsapp/types.ts";
import type { IInboundReplyRef } from "./whatsapp/types.ts";

/** Shape written to `messages.reply_to` (mirrors IMessageReplyRef on the front). */
export interface IStoredReplyRef {
  messageId?: string;
  providerMessageId?: string;
  text?: string;
  mediaType?: string;
  direction?: "in" | "out";
}

/** Candidate rows scanned per lookup. The `like` below is a broad filter; the
 *  exact match happens in pickReplyMatch, and a handful of candidates is more
 *  than a unique hash can realistically produce. */
const CANDIDATE_LIMIT = 5;

interface IQuotedRow {
  id: string;
  provider_message_id: string;
  text: string | null;
  media_type: string | null;
  direction: "in" | "out";
}

/** `text`/`unknown` are not media discriminators — they map to a null column. */
function toMediaType(contentType: string | undefined): string | undefined {
  if (!contentType) return undefined;
  return (MEDIA_DISCRIMINATOR_TYPES as readonly string[]).includes(contentType)
    ? contentType
    : undefined;
}

export async function resolveReplyRef(
  admin: SupabaseClient,
  conversationId: string,
  ref: IInboundReplyRef | undefined,
): Promise<IStoredReplyRef | null> {
  const rawId = ref?.providerMessageId;
  if (!rawId) return null;

  const { data } = await admin
    .from("messages")
    .select("id, provider_message_id, text, media_type, direction")
    .eq("conversation_id", conversationId)
    .like("provider_message_id", `%${rawId}`)
    .limit(CANDIDATE_LIMIT);

  const hit = pickReplyMatch((data ?? []) as unknown as IQuotedRow[], rawId);

  if (hit) {
    // Our own row is the better source than the provider's `body`: it carries
    // the media type and the text exactly as the thread renders it.
    return {
      messageId: hit.id,
      providerMessageId: hit.provider_message_id,
      text: truncateQuotedText(hit.text),
      mediaType: hit.media_type ?? undefined,
      direction: hit.direction,
    };
  }

  // Orphan quote — the original never reached our history (older than the
  // import, or a chat we never synced). The snapshot still renders; the UI
  // just won't make it clickable.
  return {
    providerMessageId: rawId,
    text: truncateQuotedText(ref?.text),
    mediaType: toMediaType(ref?.mediaType),
  };
}
