/**
 * Shared WAHA outbound dispatch (persist + send + persist).
 *
 * `waha-send/index.ts` (manual send, via caller JWT) and
 * `scheduled-send-worker/index.ts` (server-side scheduled dispatch, via
 * service_role) both need the exact same steps for a `waha` account:
 * resolve session/server, insert the queued `messages` row, call the WAHA
 * REST API, flip the row to sent/failed, touch the conversation, audit.
 *
 * Extracted here so the two callers never drift. The scheduled-send path
 * never had this at all (it always went through the generic
 * `buildWhatsAppEngine`, which has no `waha` branch by isolation design —
 * PRDs 112/113), so every scheduled send from a WAHA conversation failed
 * with `VALIDATION_ERROR: Engine WhatsApp desconhecido: waha` (found
 * 2026-07-12 via a real failed `scheduled_sends` row).
 *
 * Edge-runtime module (Deno): esm.sh + service_role. NOT part of the
 * src/providers/whatsapp mirror (that tree is wiped/regenerated by the sync
 * script), so it lives directly under _shared/ — same as
 * whatsappSendAdapter.ts.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.107.0";
import { bestEffortAudit } from "./audit.ts";
import { createSecretResolver } from "./secrets.ts";
import { WhatsAppProviderError } from "./whatsapp/errors.ts";
import { sendWahaMedia, sendWahaText } from "./whatsapp/waha/send.ts";
import type { IWahaSessionTarget } from "./whatsapp/waha/session.ts";

export interface IWahaDispatchResult {
  messageId: string;
  providerMessageId: string;
}

interface IWahaTarget extends IWahaSessionTarget {
  apiKey: string;
  toPhone: string;
}

/** Resolves the WAHA session/server/recipient for a conversation. Throws VALIDATION_ERROR on any gap. */
async function resolveWahaTarget(
  admin: SupabaseClient,
  conversationId: string,
): Promise<IWahaTarget> {
  const { data: conversation } = await admin
    .from("conversations")
    .select("id, whatsapp_account_id, customers(phone)")
    .eq("id", conversationId)
    .maybeSingle();
  if (!conversation?.whatsapp_account_id) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conversa sem conta WhatsApp associada",
    );
  }

  const { data: account } = await admin
    .from("whatsapp_accounts")
    .select("id, provider, provider_config, waha_server_id")
    .eq("id", conversation.whatsapp_account_id as string)
    .maybeSingle();
  if (!account || account.provider !== "waha") {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conta associada não é uma sessão WAHA",
    );
  }
  const sessionName = String(
    (account.provider_config as Record<string, unknown> | null)?.sessionName ?? "",
  );
  if (!sessionName) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Sessão WAHA sem sessionName configurado",
    );
  }

  const { data: server } = await admin
    .from("waha_servers")
    .select("base_url, api_key_ref")
    .eq("id", account.waha_server_id as string)
    .maybeSingle();
  if (!server) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Servidor WAHA não encontrado");
  }
  const baseUrl = String(server.base_url ?? "").replace(/\/+$/, "");
  const apiKey = await createSecretResolver(admin)(String(server.api_key_ref ?? ""));
  if (!apiKey) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Chave da API do servidor WAHA não definida",
    );
  }

  const toPhone = (conversation as unknown as { customers?: { phone?: string } }).customers
    ?.phone;
  if (!toPhone) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Cliente sem telefone cadastrado");
  }

  return { baseUrl, sessionName, apiKey, toPhone };
}

interface IPersistAndDispatchArgs {
  conversationId: string;
  storeId: string;
  sellerId: string | null;
  messageId?: string;
  text: string;
  mediaType?: "image" | "audio" | "video" | "document" | null;
  mediaUrl?: string | null;
  fileName?: string | null;
  send: (target: IWahaTarget) => Promise<{ providerMessageId: string }>;
}

async function persistAndDispatch(
  admin: SupabaseClient,
  args: IPersistAndDispatchArgs,
): Promise<IWahaDispatchResult> {
  const target = await resolveWahaTarget(admin, args.conversationId);

  const messageId = args.messageId ?? crypto.randomUUID();
  const { error: insertErr } = await admin.from("messages").insert({
    id: messageId,
    conversation_id: args.conversationId,
    direction: "out",
    author_type: "seller",
    author_id: args.sellerId,
    provider: "waha",
    text: args.text,
    media_type: args.mediaType ?? null,
    media_url: args.mediaUrl ?? null,
    media_filename: args.fileName ?? null,
    status: "queued",
    sent_at: new Date().toISOString(),
  });
  if (insertErr) throw new Error(`Falha ao registrar a mensagem: ${insertErr.message}`);

  try {
    const result = await args.send(target);
    await admin
      .from("messages")
      .update({ status: "sent", provider_message_id: result.providerMessageId })
      .eq("id", messageId);
    await admin
      .from("conversations")
      .update({ last_message_at: new Date().toISOString() })
      .eq("id", args.conversationId);
    if (args.sellerId) {
      await bestEffortAudit(admin, {
        store_id: args.storeId,
        actor_id: args.sellerId,
        action: "whatsapp_message_sent",
        resource: "conversation",
        resource_id: args.conversationId,
        after: { provider: "waha", messageId, providerMessageId: result.providerMessageId },
      });
    }
    return { messageId, providerMessageId: result.providerMessageId };
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    await admin
      .from("messages")
      .update({ status: "failed", failure_reason: reason })
      .eq("id", messageId);
    throw err;
  }
}

export async function dispatchWahaText(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    text: string;
    sellerId: string | null;
    messageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    ...input,
    send: (target) =>
      sendWahaText(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        text: input.text,
      }),
  });
}

export async function dispatchWahaMedia(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    mediaUrl: string;
    mediaType: "image" | "audio" | "video" | "document";
    fileName?: string;
    caption?: string;
    sellerId: string | null;
    messageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    conversationId: input.conversationId,
    storeId: input.storeId,
    sellerId: input.sellerId,
    messageId: input.messageId,
    text: input.caption ?? "",
    mediaType: input.mediaType,
    mediaUrl: input.mediaUrl,
    fileName: input.fileName,
    send: (target) =>
      sendWahaMedia(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        mediaType: input.mediaType,
        mediaUrl: input.mediaUrl,
        filename: input.fileName,
        caption: input.caption,
      }),
  });
}
