/**
 * Shared WAHA outbound dispatch (persist + send + persist).
 *
 * `waha-send/index.ts` (manual send, via caller JWT) and
 * `scheduled-send-worker/index.ts` (server-side scheduled dispatch, via
 * service_role) both need the exact same steps for a `waha` account:
 * resolve session/server, insert the queued `messages` row, call the WAHA
 * REST API, flip the row to sent/failed, touch the conversation, audit.
 *
 * Extracted here so the two callers never drift. The scheduled-send path
 * never had this at all (it always went through the generic
 * `buildWhatsAppEngine`, which has no `waha` branch by isolation design —
 * PRDs 112/113), so every scheduled send from a WAHA conversation failed
 * with `VALIDATION_ERROR: Engine WhatsApp desconhecido: waha` (found
 * 2026-07-12 via a real failed `scheduled_sends` row).
 *
 * Edge-runtime module (Deno): esm.sh + service_role. NOT part of the
 * src/providers/whatsapp mirror (that tree is wiped/regenerated by the sync
 * script), so it lives directly under _shared/ — same as
 * whatsappSendAdapter.ts.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.107.0";
import { bestEffortAudit } from "./audit.ts";
import { createSecretResolver } from "./secrets.ts";
import { truncateQuotedText } from "./whatsapp/waha/replyRef.ts";
import type { IStoredReplyRef } from "./replyRef.ts";
import { WhatsAppProviderError } from "./whatsapp/errors.ts";
import { extractLidChatId, sendWahaMedia, sendWahaText } from "./whatsapp/waha/send.ts";
import type { IWahaSessionTarget } from "./whatsapp/waha/session.ts";

export interface IWahaDispatchResult {
  messageId: string;
  providerMessageId: string;
}

interface IWahaTarget extends IWahaSessionTarget {
  apiKey: string;
  toPhone: string;
  /** Verbatim chat JID (e.g. `123@lid`) when the contact has no resolvable phone. */
  chatId?: string;
}

export interface IWahaRecipient {
  toPhone: string;
  /** Set only on the lid last-resort path — passed verbatim to the WAHA API. */
  chatId?: string;
}

/**
 * Resolves WHO a conversation's outbound WAHA message goes to.
 *
 * Resolution order (Funnel Frente 3 — PR #331 — made lead-only conversations
 * the norm: the webhook now creates a Lead for unknown numbers and the
 * Frente B migration relinked ~2.4k historical conversations from placeholder
 * customers to leads, so `customers(phone)` alone stopped covering most rows):
 *
 *   1. `customers.phone`  — conversations still linked to a real customer;
 *   2. `leads.phone`      — lead-only conversations (the webhook stores the
 *                            canonical number, lid already resolved);
 *   3. `@lid` chat JID    — last resort for contacts with no resolvable
 *                            phone at all, extracted from the latest inbound
 *                            message id (WhatsApp itself addresses these
 *                            privacy-locked chats by lid).
 *
 * Returns null when none of the three resolves — callers raise their own
 * 422 ("Contato sem telefone cadastrado"). Shared by `waha-send`,
 * `scheduled-send-worker` (via resolveWahaTarget below) and
 * `sdr-respond/dispatch.ts` so the three paths never drift again.
 */
export async function resolveWahaRecipient(
  admin: SupabaseClient,
  conversationId: string,
  known?: { customerPhone?: string | null; leadId?: string | null },
): Promise<IWahaRecipient | null> {
  let customerPhone = known?.customerPhone ?? null;
  let leadId = known?.leadId ?? null;
  if (known === undefined) {
    const { data: conversation } = await admin
      .from("conversations")
      .select("lead_id, customers(phone)")
      .eq("id", conversationId)
      .maybeSingle();
    const row = conversation as unknown as {
      lead_id?: string | null;
      customers?: { phone?: string | null } | null;
    } | null;
    customerPhone = row?.customers?.phone ?? null;
    leadId = row?.lead_id ?? null;
  }

  if (customerPhone) return { toPhone: customerPhone };

  if (leadId) {
    const { data: lead } = await admin
      .from("leads")
      .select("phone")
      .eq("id", leadId)
      .maybeSingle();
    const leadPhone = (lead?.phone as string | null) ?? null;
    if (leadPhone) return { toPhone: leadPhone };
  }

  const { data: lastLidInbound } = await admin
    .from("messages")
    .select("provider_message_id")
    .eq("conversation_id", conversationId)
    .eq("direction", "in")
    .like("provider_message_id", "%@lid_%")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  const chatId = extractLidChatId(String(lastLidInbound?.provider_message_id ?? ""));
  if (chatId) return { toPhone: "", chatId };

  return null;
}

/** Resolves the WAHA session/server/recipient for a conversation. Throws VALIDATION_ERROR on any gap. */
async function resolveWahaTarget(
  admin: SupabaseClient,
  conversationId: string,
): Promise<IWahaTarget> {
  const { data: conversation } = await admin
    .from("conversations")
    .select("id, whatsapp_account_id, lead_id, customers(phone)")
    .eq("id", conversationId)
    .maybeSingle();
  if (!conversation?.whatsapp_account_id) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conversa sem conta WhatsApp associada",
    );
  }

  const { data: account } = await admin
    .from("whatsapp_accounts")
    .select("id, provider, provider_config, waha_server_id")
    .eq("id", conversation.whatsapp_account_id as string)
    .maybeSingle();
  if (!account || account.provider !== "waha") {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conta associada não é uma sessão WAHA",
    );
  }
  const sessionName = String(
    (account.provider_config as Record<string, unknown> | null)?.sessionName ?? "",
  );
  if (!sessionName) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Sessão WAHA sem sessionName configurado",
    );
  }

  const { data: server } = await admin
    .from("waha_servers")
    .select("base_url, api_key_ref")
    .eq("id", account.waha_server_id as string)
    .maybeSingle();
  if (!server) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Servidor WAHA não encontrado");
  }
  const baseUrl = String(server.base_url ?? "").replace(/\/+$/, "");
  const apiKey = await createSecretResolver(admin)(String(server.api_key_ref ?? ""));
  if (!apiKey) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Chave da API do servidor WAHA não definida",
    );
  }

  const row = conversation as unknown as {
    customers?: { phone?: string | null } | null;
    lead_id?: string | null;
  };
  const recipient = await resolveWahaRecipient(admin, conversationId, {
    customerPhone: row.customers?.phone ?? null,
    leadId: row.lead_id ?? null,
  });
  if (!recipient) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Contato sem telefone cadastrado");
  }

  return { baseUrl, sessionName, apiKey, toPhone: recipient.toPhone, chatId: recipient.chatId };
}

/**
 * Loads the quoted message by OUR id and builds both halves of the quote: the
 * snapshot persisted on the new row, and the serialized provider id WAHA needs
 * in `reply_to`.
 *
 * The client sends only the uuid — never the snapshot — so a tampered payload
 * can't fabricate a quote of a message the conversation doesn't own (the
 * lookup is scoped to the conversation).
 *
 * Returns nulls when the target can't be quoted (wrong conversation, or it
 * never reached WhatsApp so there is no provider id). The send then proceeds
 * WITHOUT the quote instead of failing: the UI already blocks that case
 * (canReplyTo), so this is defense-in-depth, and losing a citation is far
 * better than losing the message.
 */
async function loadReplyTarget(
  admin: SupabaseClient,
  conversationId: string,
  replyToMessageId: string | undefined,
): Promise<{ snapshot: IStoredReplyRef | null; providerMessageId: string | null }> {
  if (!replyToMessageId) return { snapshot: null, providerMessageId: null };

  const { data } = await admin
    .from("messages")
    .select("id, provider_message_id, text, media_type, direction")
    .eq("id", replyToMessageId)
    .eq("conversation_id", conversationId)
    .maybeSingle();

  const providerMessageId = (data?.provider_message_id as string | null) ?? null;
  if (!data || !providerMessageId) return { snapshot: null, providerMessageId: null };

  return {
    snapshot: {
      messageId: data.id as string,
      providerMessageId,
      text: truncateQuotedText(data.text as string | null),
      mediaType: (data.media_type as string | null) ?? undefined,
      direction: data.direction as "in" | "out",
    },
    providerMessageId,
  };
}

interface IPersistAndDispatchArgs {
  conversationId: string;
  storeId: string;
  sellerId: string | null;
  messageId?: string;
  text: string;
  mediaType?: "image" | "audio" | "video" | "document" | null;
  mediaUrl?: string | null;
  fileName?: string | null;
  /** Our id of the message being quoted (optional). */
  replyToMessageId?: string;
  send: (
    target: IWahaTarget,
    replyToProviderMessageId: string | null,
  ) => Promise<{ providerMessageId: string }>;
}

async function persistAndDispatch(
  admin: SupabaseClient,
  args: IPersistAndDispatchArgs,
): Promise<IWahaDispatchResult> {
  const target = await resolveWahaTarget(admin, args.conversationId);
  const reply = await loadReplyTarget(admin, args.conversationId, args.replyToMessageId);

  const messageId = args.messageId ?? crypto.randomUUID();
  const { error: insertErr } = await admin.from("messages").insert({
    id: messageId,
    conversation_id: args.conversationId,
    direction: "out",
    author_type: "seller",
    author_id: args.sellerId,
    provider: "waha",
    text: args.text,
    media_type: args.mediaType ?? null,
    media_url: args.mediaUrl ?? null,
    media_filename: args.fileName ?? null,
    reply_to: reply.snapshot,
    status: "queued",
    sent_at: new Date().toISOString(),
  });
  if (insertErr) throw new Error(`Falha ao registrar a mensagem: ${insertErr.message}`);

  try {
    const result = await args.send(target, reply.providerMessageId);
    await admin
      .from("messages")
      .update({ status: "sent", provider_message_id: result.providerMessageId })
      .eq("id", messageId);
    await admin
      .from("conversations")
      .update({ last_message_at: new Date().toISOString() })
      .eq("id", args.conversationId);
    if (args.sellerId) {
      await bestEffortAudit(admin, {
        store_id: args.storeId,
        actor_id: args.sellerId,
        action: "whatsapp_message_sent",
        resource: "conversation",
        resource_id: args.conversationId,
        after: { provider: "waha", messageId, providerMessageId: result.providerMessageId },
      });
    }
    return { messageId, providerMessageId: result.providerMessageId };
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    await admin
      .from("messages")
      .update({ status: "failed", failure_reason: reason })
      .eq("id", messageId);
    throw err;
  }
}

export async function dispatchWahaText(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    text: string;
    sellerId: string | null;
    messageId?: string;
    replyToMessageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    ...input,
    send: (target, replyToProviderMessageId) =>
      sendWahaText(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        chatId: target.chatId,
        text: input.text,
        ...(replyToProviderMessageId ? { replyTo: replyToProviderMessageId } : {}),
      }),
  });
}

export async function dispatchWahaMedia(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    mediaUrl: string;
    mediaType: "image" | "audio" | "video" | "document";
    fileName?: string;
    caption?: string;
    /** Byte size of the file — lets a WAHA video route inline vs. as a document. */
    sizeBytes?: number;
    sellerId: string | null;
    messageId?: string;
    replyToMessageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    conversationId: input.conversationId,
    storeId: input.storeId,
    sellerId: input.sellerId,
    messageId: input.messageId,
    text: input.caption ?? "",
    mediaType: input.mediaType,
    mediaUrl: input.mediaUrl,
    fileName: input.fileName,
    replyToMessageId: input.replyToMessageId,
    send: (target, replyToProviderMessageId) =>
      sendWahaMedia(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        chatId: target.chatId,
        mediaType: input.mediaType,
        mediaUrl: input.mediaUrl,
        filename: input.fileName,
        caption: input.caption,
        sizeBytes: input.sizeBytes,
        ...(replyToProviderMessageId ? { replyTo: replyToProviderMessageId } : {}),
      }),
  });
}
