/**
 * Shared WAHA outbound dispatch (persist + send + persist).
 *
 * `waha-send/index.ts` (manual send, via caller JWT) and
 * `scheduled-send-worker/index.ts` (server-side scheduled dispatch, via
 * service_role) both need the exact same steps for a `waha` account:
 * resolve session/server, insert the queued `messages` row, call the WAHA
 * REST API, flip the row to sent/failed, touch the conversation, audit.
 *
 * Extracted here so the two callers never drift. The scheduled-send path
 * never had this at all (it always went through the generic
 * `buildWhatsAppEngine`, which has no `waha` branch by isolation design —
 * PRDs 112/113), so every scheduled send from a WAHA conversation failed
 * with `VALIDATION_ERROR: Engine WhatsApp desconhecido: waha` (found
 * 2026-07-12 via a real failed `scheduled_sends` row).
 *
 * Edge-runtime module (Deno): esm.sh + service_role. NOT part of the
 * src/providers/whatsapp mirror (that tree is wiped/regenerated by the sync
 * script), so it lives directly under _shared/ — same as
 * whatsappSendAdapter.ts.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.107.0";
import { bestEffortAudit } from "./audit.ts";
import { createSecretResolver } from "./secrets.ts";
import { truncateQuotedText } from "./whatsapp/waha/replyRef.ts";
import type { IStoredReplyRef } from "./replyRef.ts";
import { WhatsAppProviderError } from "./whatsapp/errors.ts";
import {
  extractChatJid,
  isRecipientRejection,
  sendWahaMedia,
  sendWahaText,
} from "./whatsapp/waha/send.ts";
import type { IWahaSessionTarget } from "./whatsapp/waha/session.ts";

export interface IWahaDispatchResult {
  messageId: string;
  providerMessageId: string;
}

interface IWahaTarget extends IWahaSessionTarget {
  apiKey: string;
  toPhone: string;
  /** Verbatim chat JID (e.g. `123@lid`) when the contact has no resolvable phone. */
  chatId?: string;
}

export interface IWahaRecipient {
  /**
   * Registry phone (`customers.phone` / `leads.phone`). Used as the address
   * when the conversation has no chat JID, and as the fallback when it has one
   * but WAHA rejects it.
   */
  toPhone: string;
  /** The chat's own JID (`@lid`/`@c.us`) — the primary address, sent verbatim. */
  chatId?: string;
}

/**
 * Reads the chat's own address off the latest inbound message of a
 * conversation. A WAHA message id serializes as `{fromMe}_{chatJid}_{hash}`,
 * so every inbound carries the JID WhatsApp itself uses for that chat.
 *
 * INBOUND only, deliberately: an inbound is proof of who is on the other side.
 * An outbound id would echo back whatever address WE dialled — including a
 * wrong one — which is exactly the state this resolver exists to escape.
 *
 * Looks at the last few rows rather than strictly the last: `provider_message_id`
 * is nullable (imported history) and a group JID yields no usable address.
 */
async function resolveChatJid(
  admin: SupabaseClient,
  conversationId: string,
): Promise<string | null> {
  const { data: inbound } = await admin
    .from("messages")
    .select("provider_message_id")
    .eq("conversation_id", conversationId)
    .eq("direction", "in")
    .not("provider_message_id", "is", null)
    .order("created_at", { ascending: false })
    .limit(5);
  for (const row of (inbound ?? []) as Array<{ provider_message_id?: string | null }>) {
    const jid = extractChatJid(String(row.provider_message_id ?? ""));
    if (jid) return jid;
  }
  return null;
}

/**
 * Resolves WHERE a conversation's outbound WAHA message goes.
 *
 * Resolution order:
 *
 *   0. the chat's own JID (`@lid`/`@c.us`) taken from the latest inbound —
 *      WhatsApp's own address for this thread, and the only field that cannot
 *      disagree with reality;
 *   1. `customers.phone`  — conversations linked to a customer;
 *   2. `leads.phone`      — lead-only conversations (Funnel Frente 3 / PR #331
 *                            made these the norm).
 *
 * The registry phone used to come FIRST, which made a CRM field decide where a
 * WhatsApp message goes. It is not an address: `conversations` stores no phone
 * of its own, so re-anchoring a conversation onto another contact silently
 * re-routes every future reply. That is the 2026-08-11 CATTO failure —
 * `reanchor_converted_lead_conversations` moved a buyer's thread onto his
 * company's customer row (whose DINTEC phone is the company LANDLINE) and
 * nulled the `lead_id` that held his mobile; replies then dialled a number with
 * no WhatsApp account (opaque GOWS 500) while the same text sent from the
 * seller's own handset reached him fine, addressed by lid.
 *
 * Both fields are returned when both resolve: the caller dispatches to `chatId`
 * and falls back to `toPhone` if WAHA rejects it (see persistAndDispatch).
 *
 * Returns null when nothing resolves — callers raise their own 422 ("Contato
 * sem telefone cadastrado"). Shared by `waha-send`, `scheduled-send-worker`
 * (via resolveWahaTarget below) and `sdr-respond/dispatch.ts` so the three
 * paths never drift again.
 */
export async function resolveWahaRecipient(
  admin: SupabaseClient,
  conversationId: string,
  known?: { customerPhone?: string | null; leadId?: string | null },
): Promise<IWahaRecipient | null> {
  let customerPhone = known?.customerPhone ?? null;
  let leadId = known?.leadId ?? null;
  if (known === undefined) {
    const { data: conversation } = await admin
      .from("conversations")
      .select("lead_id, customers(phone)")
      .eq("id", conversationId)
      .maybeSingle();
    const row = conversation as unknown as {
      lead_id?: string | null;
      customers?: { phone?: string | null } | null;
    } | null;
    customerPhone = row?.customers?.phone ?? null;
    leadId = row?.lead_id ?? null;
  }

  let registryPhone = customerPhone;
  if (!registryPhone && leadId) {
    const { data: lead } = await admin.from("leads").select("phone").eq("id", leadId).maybeSingle();
    registryPhone = (lead?.phone as string | null) ?? null;
  }

  const chatId = await resolveChatJid(admin, conversationId);
  if (!chatId && !registryPhone) return null;
  return { toPhone: registryPhone ?? "", chatId: chatId ?? undefined };
}

/** Resolves the WAHA session/server/recipient for a conversation. Throws VALIDATION_ERROR on any gap. */
async function resolveWahaTarget(
  admin: SupabaseClient,
  conversationId: string,
): Promise<IWahaTarget> {
  const { data: conversation } = await admin
    .from("conversations")
    .select("id, whatsapp_account_id, lead_id, customers(phone)")
    .eq("id", conversationId)
    .maybeSingle();
  if (!conversation?.whatsapp_account_id) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conversa sem conta WhatsApp associada",
    );
  }

  const { data: account } = await admin
    .from("whatsapp_accounts")
    .select("id, provider, provider_config, waha_server_id")
    .eq("id", conversation.whatsapp_account_id as string)
    .maybeSingle();
  if (!account || account.provider !== "waha") {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Conta associada não é uma sessão WAHA",
    );
  }
  const sessionName = String(
    (account.provider_config as Record<string, unknown> | null)?.sessionName ?? "",
  );
  if (!sessionName) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Sessão WAHA sem sessionName configurado",
    );
  }

  const { data: server } = await admin
    .from("waha_servers")
    .select("base_url, api_key_ref")
    .eq("id", account.waha_server_id as string)
    .maybeSingle();
  if (!server) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Servidor WAHA não encontrado");
  }
  const baseUrl = String(server.base_url ?? "").replace(/\/+$/, "");
  const apiKey = await createSecretResolver(admin)(String(server.api_key_ref ?? ""));
  if (!apiKey) {
    throw new WhatsAppProviderError(
      "VALIDATION_ERROR",
      422,
      "Chave da API do servidor WAHA não definida",
    );
  }

  const row = conversation as unknown as {
    customers?: { phone?: string | null } | null;
    lead_id?: string | null;
  };
  const recipient = await resolveWahaRecipient(admin, conversationId, {
    customerPhone: row.customers?.phone ?? null,
    leadId: row.lead_id ?? null,
  });
  if (!recipient) {
    throw new WhatsAppProviderError("VALIDATION_ERROR", 422, "Contato sem telefone cadastrado");
  }

  return { baseUrl, sessionName, apiKey, toPhone: recipient.toPhone, chatId: recipient.chatId };
}

/**
 * Loads the quoted message by OUR id and builds both halves of the quote: the
 * snapshot persisted on the new row, and the serialized provider id WAHA needs
 * in `reply_to`.
 *
 * The client sends only the uuid — never the snapshot — so a tampered payload
 * can't fabricate a quote of a message the conversation doesn't own (the
 * lookup is scoped to the conversation).
 *
 * Returns nulls when the target can't be quoted (wrong conversation, or it
 * never reached WhatsApp so there is no provider id). The send then proceeds
 * WITHOUT the quote instead of failing: the UI already blocks that case
 * (canReplyTo), so this is defense-in-depth, and losing a citation is far
 * better than losing the message.
 */
async function loadReplyTarget(
  admin: SupabaseClient,
  conversationId: string,
  replyToMessageId: string | undefined,
): Promise<{ snapshot: IStoredReplyRef | null; providerMessageId: string | null }> {
  if (!replyToMessageId) return { snapshot: null, providerMessageId: null };

  const { data } = await admin
    .from("messages")
    .select("id, provider_message_id, text, media_type, direction")
    .eq("id", replyToMessageId)
    .eq("conversation_id", conversationId)
    .maybeSingle();

  const providerMessageId = (data?.provider_message_id as string | null) ?? null;
  if (!data || !providerMessageId) return { snapshot: null, providerMessageId: null };

  return {
    snapshot: {
      messageId: data.id as string,
      providerMessageId,
      text: truncateQuotedText(data.text as string | null),
      mediaType: (data.media_type as string | null) ?? undefined,
      direction: data.direction as "in" | "out",
    },
    providerMessageId,
  };
}

interface IPersistAndDispatchArgs {
  conversationId: string;
  storeId: string;
  sellerId: string | null;
  messageId?: string;
  text: string;
  mediaType?: "image" | "audio" | "video" | "document" | null;
  mediaUrl?: string | null;
  fileName?: string | null;
  /** Our id of the message being quoted (optional). */
  replyToMessageId?: string;
  send: (
    target: IWahaTarget,
    replyToProviderMessageId: string | null,
  ) => Promise<{ providerMessageId: string }>;
}

/**
 * Dispatches to the chat's own JID and, only if WAHA answers REJECTING that
 * address, retries once against the registry phone.
 *
 * Why the safety net: addressing by `@lid` is what WhatsApp itself does for a
 * privacy-locked chat, but until now the lid path was never exercised by a
 * real platform send (the fallback existed with a zero population). Making it
 * the primary address without a retreat would bet ~70 working conversations on
 * an untested route. The retry costs one extra call in the rare failure case
 * and can never lose a message.
 *
 * Only a rejection retries — never a timeout (see isRecipientRejection): WAHA
 * finishes the send after we hang up, so retrying a transport failure would
 * risk delivering the same message twice.
 */
export async function withRecipientFallback<T>(
  recipient: IWahaRecipient,
  send: (address: IWahaRecipient) => Promise<T>,
): Promise<T> {
  try {
    return await send(recipient);
  } catch (err) {
    if (!recipient.chatId || !recipient.toPhone || !isRecipientRejection(err)) throw err;
    console.warn(
      JSON.stringify({
        level: "warn",
        msg: "waha send: chat JID rejected, retrying on the registry phone",
        chatId: recipient.chatId,
        error: err instanceof Error ? err.message : String(err),
      }),
    );
    return await send({ toPhone: recipient.toPhone, chatId: undefined });
  }
}

async function persistAndDispatch(
  admin: SupabaseClient,
  args: IPersistAndDispatchArgs,
): Promise<IWahaDispatchResult> {
  const target = await resolveWahaTarget(admin, args.conversationId);
  const reply = await loadReplyTarget(admin, args.conversationId, args.replyToMessageId);

  const messageId = args.messageId ?? crypto.randomUUID();
  const { error: insertErr } = await admin.from("messages").insert({
    id: messageId,
    conversation_id: args.conversationId,
    direction: "out",
    author_type: "seller",
    author_id: args.sellerId,
    provider: "waha",
    text: args.text,
    media_type: args.mediaType ?? null,
    media_url: args.mediaUrl ?? null,
    media_filename: args.fileName ?? null,
    reply_to: reply.snapshot,
    status: "queued",
    sent_at: new Date().toISOString(),
  });
  if (insertErr) throw new Error(`Falha ao registrar a mensagem: ${insertErr.message}`);

  try {
    // Spread the address FIELD BY FIELD: `{ ...target, ...address }` would keep
    // the rejected `chatId` on the retry, since the fallback address simply
    // omits the key rather than setting it to undefined.
    const result = await withRecipientFallback(target, (address) =>
      args.send(
        { ...target, toPhone: address.toPhone, chatId: address.chatId },
        reply.providerMessageId,
      ),
    );
    await admin
      .from("messages")
      .update({ status: "sent", provider_message_id: result.providerMessageId })
      .eq("id", messageId);
    await admin
      .from("conversations")
      .update({ last_message_at: new Date().toISOString() })
      .eq("id", args.conversationId);
    if (args.sellerId) {
      await bestEffortAudit(admin, {
        store_id: args.storeId,
        actor_id: args.sellerId,
        action: "whatsapp_message_sent",
        resource: "conversation",
        resource_id: args.conversationId,
        after: { provider: "waha", messageId, providerMessageId: result.providerMessageId },
      });
    }
    return { messageId, providerMessageId: result.providerMessageId };
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    await admin
      .from("messages")
      .update({ status: "failed", failure_reason: reason })
      .eq("id", messageId);
    throw err;
  }
}

export async function dispatchWahaText(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    text: string;
    sellerId: string | null;
    messageId?: string;
    replyToMessageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    ...input,
    send: (target, replyToProviderMessageId) =>
      sendWahaText(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        chatId: target.chatId,
        text: input.text,
        ...(replyToProviderMessageId ? { replyTo: replyToProviderMessageId } : {}),
      }),
  });
}

export async function dispatchWahaMedia(
  admin: SupabaseClient,
  input: {
    conversationId: string;
    storeId: string;
    mediaUrl: string;
    mediaType: "image" | "audio" | "video" | "document";
    fileName?: string;
    caption?: string;
    /** Byte size of the file — lets a WAHA video route inline vs. as a document. */
    sizeBytes?: number;
    sellerId: string | null;
    messageId?: string;
    replyToMessageId?: string;
  },
): Promise<IWahaDispatchResult> {
  return persistAndDispatch(admin, {
    conversationId: input.conversationId,
    storeId: input.storeId,
    sellerId: input.sellerId,
    messageId: input.messageId,
    text: input.caption ?? "",
    mediaType: input.mediaType,
    mediaUrl: input.mediaUrl,
    fileName: input.fileName,
    replyToMessageId: input.replyToMessageId,
    send: (target, replyToProviderMessageId) =>
      sendWahaMedia(target.apiKey, globalThis.fetch, target, {
        toPhone: target.toPhone,
        chatId: target.chatId,
        mediaType: input.mediaType,
        mediaUrl: input.mediaUrl,
        filename: input.fileName,
        caption: input.caption,
        sizeBytes: input.sizeBytes,
        ...(replyToProviderMessageId ? { replyTo: replyToProviderMessageId } : {}),
      }),
  });
}
