/**
 * Service-role DB + engine adapters for the WhatsApp send core (PRD-115).
 *
 * `makeSendDb` and `makeEngineDeps` were inline in `whatsapp-send/index.ts`;
 * they are shared here so the `scheduled-send-worker` dispatches due sends
 * through the EXACT same database surface (persist-before-send, 24h window,
 * failover, audit) as a manual send — one behaviour, never drifting.
 *
 * Edge-runtime module (Deno): esm.sh + service_role. NOT part of the
 * src/providers/whatsapp mirror (that tree is wiped/regenerated by the sync
 * script), so it lives directly under _shared/.
 */

import type { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.107.0";
import { bestEffortAudit } from "./audit.ts";
import { createSecretResolver } from "./secrets.ts";
import { WhatsAppProviderError } from "./whatsapp/errors.ts";
import type { ISendDb } from "./whatsapp/send/core.ts";
import type { IAccountRecord } from "./whatsapp/webhook/core.ts";
import type { IFailoverAwareAccount } from "./whatsapp/failover.ts";
import type { IEngineDeps, IIntegrationLogEntry } from "./whatsapp/types.ts";

const SIGNED_URL_TTL_SECONDS = 300; // 5min — provider fetches immediately

export function makeSendDb(admin: SupabaseClient, _traceId: string): ISendDb {
  return {
    async getSendContext(conversationId) {
      const { data: conv } = await admin
        .from("conversations")
        .select("id, store_id, status, assigned_seller_id, whatsapp_account_id, customer_id")
        .eq("id", conversationId)
        .maybeSingle();
      if (!conv) return null;

      let account: IFailoverAwareAccount | null = null;
      if (conv.whatsapp_account_id) {
        const { data: row } = await admin
          .from("whatsapp_accounts")
          .select(
            "id, store_id, provider, phone_number, credentials_ref, provider_config, " +
              "current_state, state_changed_at, failover_policy, failover_account_id, is_failover_active",
          )
          .eq("id", conv.whatsapp_account_id)
          .neq("status", "disconnected")
          .maybeSingle();
        if (row) {
          account = {
            id: row.id as string,
            storeId: row.store_id as string,
            provider: row.provider as "meta" | "evolution" | "evolution-go" | "openwa",
            phoneNumber: row.phone_number as string,
            credentialsRef: row.credentials_ref as string,
            providerConfig: (row.provider_config as Record<string, unknown> | null) ?? null,
            currentState: row.current_state as IFailoverAwareAccount["currentState"],
            stateChangedAt: (row.state_changed_at as string | null) ?? null,
            failoverPolicy: row.failover_policy as IFailoverAwareAccount["failoverPolicy"],
            failoverAccountId: (row.failover_account_id as string | null) ?? null,
            isFailoverActive: Boolean(row.is_failover_active),
          };
        }
      }

      let customerPhone: string | null = null;
      let customerWhatsappStatus: string | null = null;
      if (conv.customer_id) {
        const { data: customer } = await admin
          .from("customers")
          .select("phone, whatsapp_status")
          .eq("id", conv.customer_id)
          .maybeSingle();
        customerPhone = (customer?.phone as string | undefined) ?? null;
        customerWhatsappStatus = (customer?.whatsapp_status as string | undefined) ?? null;
      }

      return {
        conversation: {
          id: conv.id as string,
          storeId: conv.store_id as string,
          status: conv.status as string,
          assignedSellerId: (conv.assigned_seller_id as string | null) ?? null,
          whatsappAccountId: (conv.whatsapp_account_id as string | null) ?? null,
        },
        account,
        customerId: (conv.customer_id as string | null) ?? null,
        customerPhone,
        customerWhatsappStatus,
      };
    },
    // PRD-120: failover (backup) account row for resolveEffectiveAccount.
    async getAccountRecord(accountId) {
      const { data: row } = await admin
        .from("whatsapp_accounts")
        .select("id, store_id, provider, phone_number, credentials_ref, provider_config")
        .eq("id", accountId)
        .maybeSingle();
      if (!row) return null;
      return {
        id: row.id as string,
        storeId: row.store_id as string,
        provider: row.provider as "meta" | "evolution" | "evolution-go" | "openwa",
        phoneNumber: row.phone_number as string,
        credentialsRef: row.credentials_ref as string,
        providerConfig: (row.provider_config as Record<string, unknown> | null) ?? null,
      } satisfies IAccountRecord;
    },
    async isWithin24hWindow(conversationId) {
      const { data, error } = await admin.rpc("is_within_24h_window", {
        p_conversation_id: conversationId,
      });
      if (error) throw new Error(`is_within_24h_window: ${error.message}`);
      return Boolean(data);
    },
    async insertQueuedMessage(input) {
      // Honor a client-provided UUID (optimistic dedup) only when well-formed —
      // a bad id would otherwise fail the whole send on the uuid column.
      const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      const useId =
        input.messageId && UUID_RE.test(input.messageId) ? input.messageId : undefined;
      const { data, error } = await admin
        .from("messages")
        .insert({
          ...(useId ? { id: useId } : {}),
          conversation_id: input.conversationId,
          direction: "out",
          author_type: "seller",
          author_id: input.sellerId,
          provider: input.provider,
          text: input.text,
          media_type: input.mediaType,
          media_url: input.mediaUrl,
          media_filename: input.fileName ?? null,
          status: "queued",
          sent_at: new Date().toISOString(),
        })
        .select("id")
        .single();
      if (error) throw new Error(`insertQueuedMessage: ${error.message}`);
      return { id: data.id as string };
    },
    async markMessageSent(messageId, providerMessageId) {
      await admin
        .from("messages")
        .update({ status: "sent", provider_message_id: providerMessageId })
        .eq("id", messageId);
    },
    async markMessageFailed(messageId, failureReason, failureCode) {
      await admin
        .from("messages")
        .update({
          status: "failed",
          failure_reason: failureReason,
          ...(failureCode ? { failure_code: failureCode } : {}),
        })
        .eq("id", messageId);
    },
    async markCustomerWhatsappInvalid(customerId) {
      await admin.from("customers").update({ whatsapp_status: "invalid" }).eq("id", customerId);
    },
    async touchConversation(conversationId, lastMessageAt) {
      await admin
        .from("conversations")
        .update({ last_message_at: lastMessageAt, updated_at: lastMessageAt })
        .eq("id", conversationId);
    },
    async setConversationStatus(conversationId, status) {
      await admin
        .from("conversations")
        .update({ status, updated_at: new Date().toISOString() })
        .eq("id", conversationId);
    },
    async createSignedMediaUrl(path) {
      const { data, error } = await admin.storage
        .from("whatsapp-media")
        .createSignedUrl(path, SIGNED_URL_TTL_SECONDS);
      if (error || !data?.signedUrl) {
        throw new WhatsAppProviderError(
          "VALIDATION_ERROR",
          422,
          `Mídia não encontrada no Storage: ${path}`,
        );
      }
      return data.signedUrl;
    },
    async audit(input) {
      await bestEffortAudit(admin, {
        store_id: input.storeId,
        actor_id: input.actorId,
        action: input.action,
        resource: input.resource,
        resource_id: input.resourceId,
        after: input.after,
      });
    },
    // Camada 2 (multi-instância): co-responsável da conversa.
    async isConversationParticipant(conversationId, sellerId) {
      const { data } = await admin
        .from("conversation_participants")
        .select("seller_id")
        .eq("conversation_id", conversationId)
        .eq("seller_id", sellerId)
        .maybeSingle();
      return Boolean(data);
    },
    // Camada 1 (multi-instância): regras OR seller/role/store da instância.
    async sellerAccessesAccount(accountId, sellerId, role, storeId) {
      const { data } = await admin
        .from("whatsapp_account_access_rules")
        .select("kind, target_value")
        .eq("whatsapp_account_id", accountId);
      const rules = data ?? [];
      return rules.some(
        (r) =>
          (r.kind === "seller" && r.target_value === sellerId) ||
          (r.kind === "role" && r.target_value === role) ||
          (r.kind === "store" && r.target_value === storeId),
      );
    },
  };
}

export function makeEngineDeps(admin: SupabaseClient, traceId: string): IEngineDeps {
  return {
    // Vault-first ("Integrações & Chaves"), env secret as fallback.
    resolveSecret: createSecretResolver(admin),
    logIntegration: async (entry: IIntegrationLogEntry) => {
      await admin.from("integration_logs").insert({
        integration_name: entry.integrationName,
        direction: entry.direction,
        endpoint: entry.endpoint,
        http_status: entry.httpStatus,
        latency_ms: entry.latencyMs,
        trace_id: entry.traceId ?? traceId,
        request_payload: entry.requestPayload,
        response_payload: entry.responsePayload,
        error_message: entry.errorMessage,
      });
    },
  };
}
