import type { ID, IWhatsAppOpenWaServer } from "@/shared/types";

export interface ICreateOpenWaServerInput {
  name: string;
  baseUrl: string;
  /** Vault secret name (pointer) — generated by the screen via generateOpenWaServerKeyRef. */
  apiKeyRef: string;
}

export interface IOpenWaServerPatch {
  name?: string;
  baseUrl?: string;
}

/**
 * Registry of OpenWA servers (platform-level, Owner-only at the RLS layer).
 * Table-only: the global key lives in the Vault and is written/rotated by the
 * Chaves screen through the `integration-secrets` Edge Function, never here.
 * `remove` is guarded by the FK `whatsapp_accounts.openwa_server_id`
 * (ON DELETE RESTRICT) — deleting a server with linked accounts fails.
 */
export interface IWhatsAppOpenWaServersProvider {
  list(): Promise<IWhatsAppOpenWaServer[]>;
  create(input: ICreateOpenWaServerInput): Promise<IWhatsAppOpenWaServer>;
  update(id: ID, patch: IOpenWaServerPatch): Promise<IWhatsAppOpenWaServer>;
  remove(id: ID): Promise<void>;
}
