import type { ID, IWhatsAppGoServer } from "@/shared/types";

export interface ICreateGoServerInput {
  name: string;
  baseUrl: string;
  /** Vault secret name (pointer) — generated by the screen via generateGoServerKeyRef. */
  apiKeyRef: string;
}

export interface IGoServerPatch {
  name?: string;
  baseUrl?: string;
}

/**
 * Registry of Evolution Go servers (platform-level, Owner-only at the RLS
 * layer). Table-only: the global key lives in the Vault and is written/rotated
 * by the Chaves screen through the `integration-secrets` Edge Function, never
 * here. `remove` is guarded by the FK `whatsapp_accounts.go_server_id`
 * (ON DELETE RESTRICT) — deleting a server with linked accounts fails.
 */
export interface IWhatsAppGoServersProvider {
  list(): Promise<IWhatsAppGoServer[]>;
  create(input: ICreateGoServerInput): Promise<IWhatsAppGoServer>;
  update(id: ID, patch: IGoServerPatch): Promise<IWhatsAppGoServer>;
  remove(id: ID): Promise<void>;
}
