export { CopilotStrip } from "./components/CopilotStrip";
export { CopilotCard } from "./components/CopilotCard";
export { CopilotFicheTab } from "./components/CopilotFicheTab";
export { CopilotPlacementField } from "./components/CopilotPlacementField";
export { CopilotSettingsProvider } from "./CopilotSettingsProvider";
export { useCopilotPanel } from "./hooks/useCopilotPanel";
export { useCopilotPlacement } from "./hooks/useCopilotPlacement";
export { useCopilotSettings } from "./hooks/useCopilotSettings";
export type { ICopilotSettingsContext } from "./hooks/useCopilotSettings";
export type { ICopilotPanelState } from "./hooks/useCopilotPanel";
