// AUTO-GENERATED by `supabase gen types` (via MCP) — DO NOT EDIT.
// Regenerate after schema migrations: see .github/workflows/gen-types.yml
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      asset_combos: {
        Row: {
          asset_ids: string[]
          created_at: string
          id: string
          owner_id: string
          store_id: string
          title: string
          updated_at: string
        }
        Insert: {
          asset_ids?: string[]
          created_at?: string
          id?: string
          owner_id: string
          store_id: string
          title: string
          updated_at?: string
        }
        Update: {
          asset_ids?: string[]
          created_at?: string
          id?: string
          owner_id?: string
          store_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "asset_combos_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "asset_combos_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      asset_favorites: {
        Row: {
          asset_id: string
          created_at: string
          seller_id: string
        }
        Insert: {
          asset_id: string
          created_at?: string
          seller_id: string
        }
        Update: {
          asset_id?: string
          created_at?: string
          seller_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "asset_favorites_asset_id_fkey"
            columns: ["asset_id"]
            isOneToOne: false
            referencedRelation: "asset_library_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "asset_favorites_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      asset_library_items: {
        Row: {
          allowed_role_ids: string[] | null
          brand: string | null
          category: string
          created_at: string
          created_by: string
          division: string
          id: string
          kind: string
          media_asset_id: string | null
          previous_version: Json | null
          product_line: string | null
          sensitivity: string
          status: string
          storage_ref: string | null
          store_id: string
          title: string
          updated_at: string
          url: string | null
          version: number
        }
        Insert: {
          allowed_role_ids?: string[] | null
          brand?: string | null
          category: string
          created_at?: string
          created_by: string
          division?: string
          id?: string
          kind: string
          media_asset_id?: string | null
          previous_version?: Json | null
          product_line?: string | null
          sensitivity?: string
          status?: string
          storage_ref?: string | null
          store_id: string
          title: string
          updated_at?: string
          url?: string | null
          version?: number
        }
        Update: {
          allowed_role_ids?: string[] | null
          brand?: string | null
          category?: string
          created_at?: string
          created_by?: string
          division?: string
          id?: string
          kind?: string
          media_asset_id?: string | null
          previous_version?: Json | null
          product_line?: string | null
          sensitivity?: string
          status?: string
          storage_ref?: string | null
          store_id?: string
          title?: string
          updated_at?: string
          url?: string | null
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "asset_library_items_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      asset_send_log: {
        Row: {
          asset_id: string
          id: string
          seller_id: string
          sent_at: string
        }
        Insert: {
          asset_id: string
          id?: string
          seller_id: string
          sent_at?: string
        }
        Update: {
          asset_id?: string
          id?: string
          seller_id?: string
          sent_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "asset_send_log_asset_id_fkey"
            columns: ["asset_id"]
            isOneToOne: false
            referencedRelation: "asset_library_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "asset_send_log_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string
          after: Json | null
          before: Json | null
          id: string
          resource: string
          resource_id: string
          store_id: string
          timestamp: string
        }
        Insert: {
          action: string
          actor_id: string
          after?: Json | null
          before?: Json | null
          id?: string
          resource: string
          resource_id: string
          store_id: string
          timestamp?: string
        }
        Update: {
          action?: string
          actor_id?: string
          after?: Json | null
          before?: Json | null
          id?: string
          resource?: string
          resource_id?: string
          store_id?: string
          timestamp?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      carteira_transfers: {
        Row: {
          auto_revert_at: string | null
          created_at: string
          created_by: string
          customer_ids: string[]
          end_date: string | null
          from_seller_id: string
          id: string
          reason: string
          start_date: string
          status: string
          store_id: string
          to_seller_id: string
          type: string
        }
        Insert: {
          auto_revert_at?: string | null
          created_at?: string
          created_by: string
          customer_ids?: string[]
          end_date?: string | null
          from_seller_id: string
          id?: string
          reason: string
          start_date: string
          status?: string
          store_id: string
          to_seller_id: string
          type: string
        }
        Update: {
          auto_revert_at?: string | null
          created_at?: string
          created_by?: string
          customer_ids?: string[]
          end_date?: string | null
          from_seller_id?: string
          id?: string
          reason?: string
          start_date?: string
          status?: string
          store_id?: string
          to_seller_id?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "carteira_transfers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "carteira_transfers_from_seller_id_fkey"
            columns: ["from_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "carteira_transfers_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "carteira_transfers_to_seller_id_fkey"
            columns: ["to_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      cash_flow_entries: {
        Row: {
          amount: number
          created_at: string
          created_by: string | null
          date: string
          description: string
          id: string
          source: string
          source_id: string | null
          status: string
          store_id: string
          type: string
        }
        Insert: {
          amount: number
          created_at?: string
          created_by?: string | null
          date: string
          description: string
          id?: string
          source: string
          source_id?: string | null
          status?: string
          store_id: string
          type: string
        }
        Update: {
          amount?: number
          created_at?: string
          created_by?: string | null
          date?: string
          description?: string
          id?: string
          source?: string
          source_id?: string | null
          status?: string
          store_id?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "cash_flow_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cash_flow_entries_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      commissions: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          base_commission: number
          base_rate: number
          base_value: number
          calculated_at: string
          closed_in_period: string | null
          created_at: string
          dispute_reason: string | null
          dispute_resolution: string | null
          dispute_resolved_at: string | null
          dispute_resolved_by: string | null
          disputed_at: string | null
          goal_bonus: number
          goal_snapshot: Json | null
          id: string
          is_split: boolean
          notes: string | null
          order_id: string
          paid_at: string | null
          paid_by: string | null
          period: string
          rate: number
          rule_snapshot: Json | null
          seller_id: string
          split_details: Json | null
          status: string
          store_id: string
          total_commission: number
          updated_at: string
          value: number
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          base_commission: number
          base_rate: number
          base_value: number
          calculated_at: string
          closed_in_period?: string | null
          created_at?: string
          dispute_reason?: string | null
          dispute_resolution?: string | null
          dispute_resolved_at?: string | null
          dispute_resolved_by?: string | null
          disputed_at?: string | null
          goal_bonus: number
          goal_snapshot?: Json | null
          id?: string
          is_split?: boolean
          notes?: string | null
          order_id: string
          paid_at?: string | null
          paid_by?: string | null
          period: string
          rate: number
          rule_snapshot?: Json | null
          seller_id: string
          split_details?: Json | null
          status: string
          store_id: string
          total_commission: number
          updated_at?: string
          value: number
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          base_commission?: number
          base_rate?: number
          base_value?: number
          calculated_at?: string
          closed_in_period?: string | null
          created_at?: string
          dispute_reason?: string | null
          dispute_resolution?: string | null
          dispute_resolved_at?: string | null
          dispute_resolved_by?: string | null
          disputed_at?: string | null
          goal_bonus?: number
          goal_snapshot?: Json | null
          id?: string
          is_split?: boolean
          notes?: string | null
          order_id?: string
          paid_at?: string | null
          paid_by?: string | null
          period?: string
          rate?: number
          rule_snapshot?: Json | null
          seller_id?: string
          split_details?: Json | null
          status?: string
          store_id?: string
          total_commission?: number
          updated_at?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "commissions_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commissions_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "commissions_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          assigned_seller_id: string | null
          channel: string
          created_at: string
          customer_id: string | null
          id: string
          is_sdr_active: boolean
          last_message_at: string
          lead_id: string | null
          linked_order_id: string | null
          status: string
          store_id: string
          tags: string[]
          unread_count: number
          updated_at: string
          whatsapp_account_id: string | null
        }
        Insert: {
          assigned_seller_id?: string | null
          channel: string
          created_at?: string
          customer_id?: string | null
          id?: string
          is_sdr_active?: boolean
          last_message_at: string
          lead_id?: string | null
          linked_order_id?: string | null
          status: string
          store_id: string
          tags?: string[]
          unread_count?: number
          updated_at?: string
          whatsapp_account_id?: string | null
        }
        Update: {
          assigned_seller_id?: string | null
          channel?: string
          created_at?: string
          customer_id?: string | null
          id?: string
          is_sdr_active?: boolean
          last_message_at?: string
          lead_id?: string | null
          linked_order_id?: string | null
          status?: string
          store_id?: string
          tags?: string[]
          unread_count?: number
          updated_at?: string
          whatsapp_account_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_assigned_seller_id_fkey"
            columns: ["assigned_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_whatsapp_account_id_fkey"
            columns: ["whatsapp_account_id"]
            isOneToOne: false
            referencedRelation: "whatsapp_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_notes: {
        Row: {
          author_id: string
          content: string
          created_at: string
          customer_id: string
          id: string
        }
        Insert: {
          author_id: string
          content: string
          created_at?: string
          customer_id: string
          id?: string
        }
        Update: {
          author_id?: string
          content?: string
          created_at?: string
          customer_id?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_notes_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customer_notes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_segments: {
        Row: {
          created_at: string
          description: string | null
          estimated_size: number | null
          filters: Json
          id: string
          name: string
          owner_id: string
          scope: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          estimated_size?: number | null
          filters?: Json
          id?: string
          name: string
          owner_id: string
          scope: string
        }
        Update: {
          created_at?: string
          description?: string | null
          estimated_size?: number | null
          filters?: Json
          id?: string
          name?: string
          owner_id?: string
          scope?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_segments_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          abc_class: string | null
          abc_share: number | null
          address: Json | null
          cnpj: string | null
          contact_name: string | null
          converted_by_seller_id: string | null
          converted_from_lead_at: string | null
          converted_from_lead_id: string | null
          cpf: string | null
          created_at: string
          email: string | null
          first_purchase_at: string | null
          full_name: string | null
          has_b2b_portal: boolean | null
          id: string
          is_guest_checkout: boolean | null
          last_purchase_at: string | null
          nome_fantasia: string | null
          overdue_titles_count: number | null
          phone: string
          portal: Json | null
          portal_contract: Json | null
          purchase_stats: Json | null
          razao_social: string | null
          seller_id: string
          status: string
          store_id: string
          tags: string[]
          type: string
        }
        Insert: {
          abc_class?: string | null
          abc_share?: number | null
          address?: Json | null
          cnpj?: string | null
          contact_name?: string | null
          converted_by_seller_id?: string | null
          converted_from_lead_at?: string | null
          converted_from_lead_id?: string | null
          cpf?: string | null
          created_at?: string
          email?: string | null
          first_purchase_at?: string | null
          full_name?: string | null
          has_b2b_portal?: boolean | null
          id?: string
          is_guest_checkout?: boolean | null
          last_purchase_at?: string | null
          nome_fantasia?: string | null
          overdue_titles_count?: number | null
          phone: string
          portal?: Json | null
          portal_contract?: Json | null
          purchase_stats?: Json | null
          razao_social?: string | null
          seller_id: string
          status: string
          store_id: string
          tags?: string[]
          type: string
        }
        Update: {
          abc_class?: string | null
          abc_share?: number | null
          address?: Json | null
          cnpj?: string | null
          contact_name?: string | null
          converted_by_seller_id?: string | null
          converted_from_lead_at?: string | null
          converted_from_lead_id?: string | null
          cpf?: string | null
          created_at?: string
          email?: string | null
          first_purchase_at?: string | null
          full_name?: string | null
          has_b2b_portal?: boolean | null
          id?: string
          is_guest_checkout?: boolean | null
          last_purchase_at?: string | null
          nome_fantasia?: string | null
          overdue_titles_count?: number | null
          phone?: string
          portal?: Json | null
          portal_contract?: Json | null
          purchase_stats?: Json | null
          razao_social?: string | null
          seller_id?: string
          status?: string
          store_id?: string
          tags?: string[]
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_converted_by_seller_id_fkey"
            columns: ["converted_by_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customers_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "customers_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      distribution_traces: {
        Row: {
          candidates_evaluated: Json
          conversation_id: string
          criterion_matched: string
          customer_id: string | null
          id: string
          lead_id: string | null
          mode: string
          selected_seller_id: string | null
          store_id: string
          timestamp: string
        }
        Insert: {
          candidates_evaluated?: Json
          conversation_id: string
          criterion_matched: string
          customer_id?: string | null
          id?: string
          lead_id?: string | null
          mode: string
          selected_seller_id?: string | null
          store_id: string
          timestamp: string
        }
        Update: {
          candidates_evaluated?: Json
          conversation_id?: string
          criterion_matched?: string
          customer_id?: string | null
          id?: string
          lead_id?: string | null
          mode?: string
          selected_seller_id?: string | null
          store_id?: string
          timestamp?: string
        }
        Relationships: [
          {
            foreignKeyName: "distribution_traces_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "distribution_traces_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "distribution_traces_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "distribution_traces_selected_seller_id_fkey"
            columns: ["selected_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "distribution_traces_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      expenses: {
        Row: {
          amount: number
          attachment_url: string | null
          category: string
          competence_date: string
          created_at: string
          created_by: string
          description: string
          due_date: string | null
          id: string
          is_recurring: boolean
          notes: string | null
          payment_date: string | null
          payment_method: string | null
          recurrence_config: Json | null
          recurrence_parent_id: string | null
          status: string
          store_id: string
          supplier: string | null
          updated_at: string
        }
        Insert: {
          amount?: number
          attachment_url?: string | null
          category: string
          competence_date: string
          created_at?: string
          created_by: string
          description: string
          due_date?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          payment_date?: string | null
          payment_method?: string | null
          recurrence_config?: Json | null
          recurrence_parent_id?: string | null
          status?: string
          store_id: string
          supplier?: string | null
          updated_at?: string
        }
        Update: {
          amount?: number
          attachment_url?: string | null
          category?: string
          competence_date?: string
          created_at?: string
          created_by?: string
          description?: string
          due_date?: string | null
          id?: string
          is_recurring?: boolean
          notes?: string | null
          payment_date?: string | null
          payment_method?: string | null
          recurrence_config?: Json | null
          recurrence_parent_id?: string | null
          status?: string
          store_id?: string
          supplier?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "expenses_recurrence_parent_id_fkey"
            columns: ["recurrence_parent_id"]
            isOneToOne: false
            referencedRelation: "expenses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      goals: {
        Row: {
          cancel_reason: string | null
          created_at: string
          created_by: string | null
          current_value: number
          division: string | null
          id: string
          level: string
          metric: string
          name: string | null
          period: Json
          progress_percent: number
          reward_description: string | null
          seller_id: string | null
          status: string | null
          store_id: string
          target_id: string
          target_value: number
          updated_at: string
        }
        Insert: {
          cancel_reason?: string | null
          created_at?: string
          created_by?: string | null
          current_value?: number
          division?: string | null
          id?: string
          level: string
          metric: string
          name?: string | null
          period: Json
          progress_percent?: number
          reward_description?: string | null
          seller_id?: string | null
          status?: string | null
          store_id: string
          target_id: string
          target_value?: number
          updated_at?: string
        }
        Update: {
          cancel_reason?: string | null
          created_at?: string
          created_by?: string | null
          current_value?: number
          division?: string | null
          id?: string
          level?: string
          metric?: string
          name?: string | null
          period?: Json
          progress_percent?: number
          reward_description?: string | null
          seller_id?: string | null
          status?: string | null
          store_id?: string
          target_id?: string
          target_value?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goals_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goals_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          conversations: string[]
          converted_to_customer_id: string | null
          created_at: string
          email: string | null
          estimated_value: number | null
          id: string
          loss_notes: string | null
          loss_reason: string | null
          name: string
          next_action_at: string | null
          origin: string
          phone: string
          seller_id: string
          stage: Json
          store_id: string
          tags: string[]
          temperature: string
          updated_at: string
        }
        Insert: {
          conversations?: string[]
          converted_to_customer_id?: string | null
          created_at?: string
          email?: string | null
          estimated_value?: number | null
          id?: string
          loss_notes?: string | null
          loss_reason?: string | null
          name: string
          next_action_at?: string | null
          origin: string
          phone: string
          seller_id: string
          stage: Json
          store_id: string
          tags?: string[]
          temperature: string
          updated_at?: string
        }
        Update: {
          conversations?: string[]
          converted_to_customer_id?: string | null
          created_at?: string
          email?: string | null
          estimated_value?: number | null
          id?: string
          loss_notes?: string | null
          loss_reason?: string | null
          name?: string
          next_action_at?: string | null
          origin?: string
          phone?: string
          seller_id?: string
          stage?: Json
          store_id?: string
          tags?: string[]
          temperature?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_converted_to_customer_id_fkey"
            columns: ["converted_to_customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      media_assets: {
        Row: {
          annotations: Json | null
          author_type: string
          classification: string | null
          content_hash: string | null
          conversation_id: string | null
          created_at: string
          customer_id: string | null
          direction: string
          file_name: string | null
          id: string
          kind: string
          linked_order_id: string | null
          linked_part_id: string | null
          linked_vehicle_id: string | null
          message_id: string | null
          mime_type: string
          ocr_text: string | null
          persisted: boolean
          sensitivity: string
          size_bytes: number
          source_expires_at: string | null
          storage_ref: string
          store_id: string
          transcription: string | null
          version: number | null
        }
        Insert: {
          annotations?: Json | null
          author_type: string
          classification?: string | null
          content_hash?: string | null
          conversation_id?: string | null
          created_at?: string
          customer_id?: string | null
          direction: string
          file_name?: string | null
          id?: string
          kind: string
          linked_order_id?: string | null
          linked_part_id?: string | null
          linked_vehicle_id?: string | null
          message_id?: string | null
          mime_type: string
          ocr_text?: string | null
          persisted?: boolean
          sensitivity?: string
          size_bytes: number
          source_expires_at?: string | null
          storage_ref: string
          store_id: string
          transcription?: string | null
          version?: number | null
        }
        Update: {
          annotations?: Json | null
          author_type?: string
          classification?: string | null
          content_hash?: string | null
          conversation_id?: string | null
          created_at?: string
          customer_id?: string | null
          direction?: string
          file_name?: string | null
          id?: string
          kind?: string
          linked_order_id?: string | null
          linked_part_id?: string | null
          linked_vehicle_id?: string | null
          message_id?: string | null
          mime_type?: string
          ocr_text?: string | null
          persisted?: boolean
          sensitivity?: string
          size_bytes?: number
          source_expires_at?: string | null
          storage_ref?: string
          store_id?: string
          transcription?: string | null
          version?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "media_assets_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_linked_order_id_fkey"
            columns: ["linked_order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_linked_part_id_fkey"
            columns: ["linked_part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_linked_vehicle_id_fkey"
            columns: ["linked_vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_assets_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          author_id: string | null
          author_type: string
          conversation_id: string
          created_at: string
          delivered_at: string | null
          direction: string
          id: string
          media_type: string | null
          media_url: string | null
          provider: string
          read_at: string | null
          sent_at: string
          status: string
          text: string
        }
        Insert: {
          author_id?: string | null
          author_type: string
          conversation_id: string
          created_at?: string
          delivered_at?: string | null
          direction: string
          id?: string
          media_type?: string | null
          media_url?: string | null
          provider: string
          read_at?: string | null
          sent_at: string
          status: string
          text?: string
        }
        Update: {
          author_id?: string | null
          author_type?: string
          conversation_id?: string
          created_at?: string
          delivered_at?: string | null
          direction?: string
          id?: string
          media_type?: string | null
          media_url?: string | null
          provider?: string
          read_at?: string | null
          sent_at?: string
          status?: string
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      model_kit_items: {
        Row: {
          default_quantity: number
          id: string
          is_optional: boolean
          kit_id: string
          note: string | null
          part_id: string
        }
        Insert: {
          default_quantity?: number
          id?: string
          is_optional?: boolean
          kit_id: string
          note?: string | null
          part_id: string
        }
        Update: {
          default_quantity?: number
          id?: string
          is_optional?: boolean
          kit_id?: string
          note?: string | null
          part_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "model_kit_items_kit_id_fkey"
            columns: ["kit_id"]
            isOneToOne: false
            referencedRelation: "model_kits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "model_kit_items_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      model_kits: {
        Row: {
          category: string
          created_at: string
          created_by: string
          id: string
          model_id: string
          name: string
          status: string
          store_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          category: string
          created_at?: string
          created_by: string
          id?: string
          model_id: string
          name: string
          status?: string
          store_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          category?: string
          created_at?: string
          created_by?: string
          id?: string
          model_id?: string
          name?: string
          status?: string
          store_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "model_kits_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "vehicle_models"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "model_kits_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_preferences: {
        Row: {
          matrix: Json
          quiet_hours: Json | null
          recipient_id: string
          recipient_type: string
          updated_at: string
        }
        Insert: {
          matrix: Json
          quiet_hours?: Json | null
          recipient_id: string
          recipient_type: string
          updated_at?: string
        }
        Update: {
          matrix?: Json
          quiet_hours?: Json | null
          recipient_id?: string
          recipient_type?: string
          updated_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          actions: Json | null
          body: string | null
          category: string
          channels: string[]
          created_at: string
          dedupe_key: string
          delivery_status: Json | null
          entity_ref: Json | null
          expires_at: string | null
          group_key: string | null
          id: string
          lifecycle: string
          metadata: Json | null
          read_at: string | null
          recipient_id: string
          recipient_type: string
          severity: string
          source: string
          status: string
          store_id: string | null
          title: string
          type: string
        }
        Insert: {
          actions?: Json | null
          body?: string | null
          category: string
          channels?: string[]
          created_at?: string
          dedupe_key: string
          delivery_status?: Json | null
          entity_ref?: Json | null
          expires_at?: string | null
          group_key?: string | null
          id?: string
          lifecycle: string
          metadata?: Json | null
          read_at?: string | null
          recipient_id: string
          recipient_type: string
          severity: string
          source: string
          status?: string
          store_id?: string | null
          title: string
          type: string
        }
        Update: {
          actions?: Json | null
          body?: string | null
          category?: string
          channels?: string[]
          created_at?: string
          dedupe_key?: string
          delivery_status?: Json | null
          entity_ref?: Json | null
          expires_at?: string | null
          group_key?: string | null
          id?: string
          lifecycle?: string
          metadata?: Json | null
          read_at?: string | null
          recipient_id?: string
          recipient_type?: string
          severity?: string
          source?: string
          status?: string
          store_id?: string | null
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          applied_to_vehicle_id: string | null
          discount: number
          id: string
          margin_value: number
          order_id: string
          part_category: string | null
          part_id: string
          part_name: string
          part_sku: string
          part_subcategory: string | null
          quantity: number
          total: number
          unit_cost: number
          unit_price: number
        }
        Insert: {
          applied_to_vehicle_id?: string | null
          discount: number
          id?: string
          margin_value: number
          order_id: string
          part_category?: string | null
          part_id: string
          part_name: string
          part_sku: string
          part_subcategory?: string | null
          quantity: number
          total: number
          unit_cost: number
          unit_price: number
        }
        Update: {
          applied_to_vehicle_id?: string | null
          discount?: number
          id?: string
          margin_value?: number
          order_id?: string
          part_category?: string | null
          part_id?: string
          part_name?: string
          part_sku?: string
          part_subcategory?: string | null
          quantity?: number
          total?: number
          unit_cost?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_applied_to_vehicle_id_fkey"
            columns: ["applied_to_vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          cancel_reason: string | null
          canceled_at: string | null
          canceled_by: string | null
          carrier: string | null
          commission_preview: Json | null
          conversation_id: string | null
          created_at: string
          customer_id: string
          customer_notes: string | null
          delivered_at: string | null
          delivery_address: Json | null
          discount: number
          division: string
          fulfillment_status: string
          id: string
          internal_notes: string | null
          nf_date: string | null
          nf_number: string | null
          notes: string | null
          number: string | null
          origin: string
          paid_at: string | null
          payment_condition: string
          payment_method: string | null
          payment_status: string
          payment_terms: string | null
          quote_id: string | null
          return_reason: string | null
          returned_at: string | null
          seller_id: string
          shipped_at: string | null
          shipping: number
          store_id: string
          subtotal: number
          total: number
          tracking_code: string | null
          updated_at: string
        }
        Insert: {
          cancel_reason?: string | null
          canceled_at?: string | null
          canceled_by?: string | null
          carrier?: string | null
          commission_preview?: Json | null
          conversation_id?: string | null
          created_at?: string
          customer_id: string
          customer_notes?: string | null
          delivered_at?: string | null
          delivery_address?: Json | null
          discount: number
          division?: string
          fulfillment_status: string
          id?: string
          internal_notes?: string | null
          nf_date?: string | null
          nf_number?: string | null
          notes?: string | null
          number?: string | null
          origin: string
          paid_at?: string | null
          payment_condition: string
          payment_method?: string | null
          payment_status: string
          payment_terms?: string | null
          quote_id?: string | null
          return_reason?: string | null
          returned_at?: string | null
          seller_id: string
          shipped_at?: string | null
          shipping: number
          store_id: string
          subtotal: number
          total: number
          tracking_code?: string | null
          updated_at?: string
        }
        Update: {
          cancel_reason?: string | null
          canceled_at?: string | null
          canceled_by?: string | null
          carrier?: string | null
          commission_preview?: Json | null
          conversation_id?: string | null
          created_at?: string
          customer_id?: string
          customer_notes?: string | null
          delivered_at?: string | null
          delivery_address?: Json | null
          discount?: number
          division?: string
          fulfillment_status?: string
          id?: string
          internal_notes?: string | null
          nf_date?: string | null
          nf_number?: string | null
          notes?: string | null
          number?: string | null
          origin?: string
          paid_at?: string | null
          payment_condition?: string
          payment_method?: string | null
          payment_status?: string
          payment_terms?: string | null
          quote_id?: string | null
          return_reason?: string | null
          returned_at?: string | null
          seller_id?: string
          shipped_at?: string | null
          shipping?: number
          store_id?: string
          subtotal?: number
          total?: number
          tracking_code?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_canceled_by_fkey"
            columns: ["canceled_by"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      parts: {
        Row: {
          active: boolean
          application_notes: string | null
          applications: Json
          average_cost: number | null
          box_quantity: number | null
          brand: string
          category: string | null
          created_at: string
          cross_references: Json | null
          description: string | null
          division: string
          equivalent_part_ids: string[]
          fiscal: Json | null
          fractionable: boolean | null
          group_label: string | null
          gtin: string | null
          id: string
          image_url: string | null
          is_original: boolean | null
          margin_percent: number
          name: string
          oem_codes: string[]
          oem_codes_text: string | null
          part_type: string | null
          price_tables: Json | null
          reference: string | null
          sefaz_checked_at: string | null
          sefaz_status: string | null
          segment: string | null
          sku: string
          stock_available: number
          stock_minimum: number
          storage_location: string | null
          store_id: string | null
          subcategory: string | null
          supplier: string
          supplier_code: string | null
          suppliers: Json | null
          unit_cost: number
          unit_of_measure: string | null
          unit_price: number
          updated_at: string
          weight_kg: number | null
        }
        Insert: {
          active?: boolean
          application_notes?: string | null
          applications?: Json
          average_cost?: number | null
          box_quantity?: number | null
          brand: string
          category?: string | null
          created_at?: string
          cross_references?: Json | null
          description?: string | null
          division?: string
          equivalent_part_ids?: string[]
          fiscal?: Json | null
          fractionable?: boolean | null
          group_label?: string | null
          gtin?: string | null
          id?: string
          image_url?: string | null
          is_original?: boolean | null
          margin_percent?: number
          name: string
          oem_codes?: string[]
          oem_codes_text?: string | null
          part_type?: string | null
          price_tables?: Json | null
          reference?: string | null
          sefaz_checked_at?: string | null
          sefaz_status?: string | null
          segment?: string | null
          sku: string
          stock_available?: number
          stock_minimum?: number
          storage_location?: string | null
          store_id?: string | null
          subcategory?: string | null
          supplier: string
          supplier_code?: string | null
          suppliers?: Json | null
          unit_cost?: number
          unit_of_measure?: string | null
          unit_price?: number
          updated_at?: string
          weight_kg?: number | null
        }
        Update: {
          active?: boolean
          application_notes?: string | null
          applications?: Json
          average_cost?: number | null
          box_quantity?: number | null
          brand?: string
          category?: string | null
          created_at?: string
          cross_references?: Json | null
          description?: string | null
          division?: string
          equivalent_part_ids?: string[]
          fiscal?: Json | null
          fractionable?: boolean | null
          group_label?: string | null
          gtin?: string | null
          id?: string
          image_url?: string | null
          is_original?: boolean | null
          margin_percent?: number
          name?: string
          oem_codes?: string[]
          oem_codes_text?: string | null
          part_type?: string | null
          price_tables?: Json | null
          reference?: string | null
          sefaz_checked_at?: string | null
          sefaz_status?: string | null
          segment?: string | null
          sku?: string
          stock_available?: number
          stock_minimum?: number
          storage_location?: string | null
          store_id?: string | null
          subcategory?: string | null
          supplier?: string
          supplier_code?: string | null
          suppliers?: Json | null
          unit_cost?: number
          unit_of_measure?: string | null
          unit_price?: number
          updated_at?: string
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "parts_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      product_indicators: {
        Row: {
          cancel_reason: string | null
          created_at: string
          created_by: string
          division: string | null
          id: string
          metric: string
          name: string
          period: Json
          reward_description: string | null
          scope_level: string
          selector: Json
          seller_id: string | null
          status: string
          store_id: string
          target_value: number
          updated_at: string
        }
        Insert: {
          cancel_reason?: string | null
          created_at: string
          created_by: string
          division?: string | null
          id?: string
          metric: string
          name: string
          period: Json
          reward_description?: string | null
          scope_level: string
          selector: Json
          seller_id?: string | null
          status: string
          store_id: string
          target_value: number
          updated_at: string
        }
        Update: {
          cancel_reason?: string | null
          created_at?: string
          created_by?: string
          division?: string | null
          id?: string
          metric?: string
          name?: string
          period?: Json
          reward_description?: string | null
          scope_level?: string
          selector?: Json
          seller_id?: string | null
          status?: string
          store_id?: string
          target_value?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_indicators_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_indicators_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          auth_user_id: string
          created_at: string
          display_name: string
          email: string | null
          role: string
          seller_id: string | null
          store_id: string
        }
        Insert: {
          auth_user_id: string
          created_at?: string
          display_name: string
          email?: string | null
          role: string
          seller_id?: string | null
          store_id: string
        }
        Update: {
          auth_user_id?: string
          created_at?: string
          display_name?: string
          email?: string | null
          role?: string
          seller_id?: string | null
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      quick_replies: {
        Row: {
          allowed_role_ids: string[] | null
          body: string
          created_at: string
          id: string
          owner_id: string
          scope: string
          shortcut: string
          store_id: string
          title: string
          updated_at: string
        }
        Insert: {
          allowed_role_ids?: string[] | null
          body: string
          created_at?: string
          id?: string
          owner_id: string
          scope: string
          shortcut: string
          store_id: string
          title: string
          updated_at?: string
        }
        Update: {
          allowed_role_ids?: string[] | null
          body?: string
          created_at?: string
          id?: string
          owner_id?: string
          scope?: string
          shortcut?: string
          store_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "quick_replies_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quick_replies_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_items: {
        Row: {
          discount: number
          id: string
          part_id: string
          part_name: string
          part_sku: string
          quantity: number
          quote_id: string
          total: number
          unit_price: number
        }
        Insert: {
          discount?: number
          id?: string
          part_id: string
          part_name: string
          part_sku: string
          quantity?: number
          quote_id: string
          total?: number
          unit_price?: number
        }
        Update: {
          discount?: number
          id?: string
          part_id?: string
          part_name?: string
          part_sku?: string
          quantity?: number
          quote_id?: string
          total?: number
          unit_price?: number
        }
        Relationships: [
          {
            foreignKeyName: "quote_items_part_id_fkey"
            columns: ["part_id"]
            isOneToOne: false
            referencedRelation: "parts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quote_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          applied_kit_ids: string[] | null
          approved_at: string | null
          approved_by: string | null
          conversation_id: string | null
          converted_at: string | null
          converted_to_order_id: string | null
          created_at: string
          customer_id: string | null
          delivery_address: Json | null
          discount: number
          discount_reason: string | null
          division: string
          id: string
          lead_id: string | null
          notes: string | null
          number: string
          origin: string
          payment_condition: string
          payment_method: string | null
          payment_terms: string | null
          rejected_reason: string | null
          requires_approval: boolean | null
          seller_id: string
          shipping: number
          status: string
          store_id: string
          subtotal: number
          total: number
          updated_at: string
          valid_until: string
        }
        Insert: {
          applied_kit_ids?: string[] | null
          approved_at?: string | null
          approved_by?: string | null
          conversation_id?: string | null
          converted_at?: string | null
          converted_to_order_id?: string | null
          created_at?: string
          customer_id?: string | null
          delivery_address?: Json | null
          discount?: number
          discount_reason?: string | null
          division?: string
          id?: string
          lead_id?: string | null
          notes?: string | null
          number: string
          origin: string
          payment_condition?: string
          payment_method?: string | null
          payment_terms?: string | null
          rejected_reason?: string | null
          requires_approval?: boolean | null
          seller_id: string
          shipping?: number
          status: string
          store_id: string
          subtotal?: number
          total?: number
          updated_at?: string
          valid_until: string
        }
        Update: {
          applied_kit_ids?: string[] | null
          approved_at?: string | null
          approved_by?: string | null
          conversation_id?: string | null
          converted_at?: string | null
          converted_to_order_id?: string | null
          created_at?: string
          customer_id?: string | null
          delivery_address?: Json | null
          discount?: number
          discount_reason?: string | null
          division?: string
          id?: string
          lead_id?: string | null
          notes?: string | null
          number?: string
          origin?: string
          payment_condition?: string
          payment_method?: string | null
          payment_terms?: string | null
          rejected_reason?: string | null
          requires_approval?: boolean | null
          seller_id?: string
          shipping?: number
          status?: string
          store_id?: string
          subtotal?: number
          total?: number
          updated_at?: string
          valid_until?: string
        }
        Relationships: [
          {
            foreignKeyName: "quotes_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      recommendations: {
        Row: {
          action_href: string | null
          created_at: string
          description: string
          id: string
          priority: string
          resolved: boolean
          resolved_at: string | null
          seller_id: string
          store_id: string
          subject_id: string
          title: string
          type: string
        }
        Insert: {
          action_href?: string | null
          created_at?: string
          description: string
          id?: string
          priority: string
          resolved?: boolean
          resolved_at?: string | null
          seller_id: string
          store_id: string
          subject_id: string
          title: string
          type: string
        }
        Update: {
          action_href?: string | null
          created_at?: string
          description?: string
          id?: string
          priority?: string
          resolved?: boolean
          resolved_at?: string | null
          seller_id?: string
          store_id?: string
          subject_id?: string
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "recommendations_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recommendations_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recommendations_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      scheduled_sends: {
        Row: {
          conversation_id: string
          created_at: string
          created_by: string
          failure_reason: string | null
          id: string
          payload: Json
          scheduled_for: string
          status: string
          store_id: string
        }
        Insert: {
          conversation_id: string
          created_at?: string
          created_by: string
          failure_reason?: string | null
          id?: string
          payload: Json
          scheduled_for: string
          status?: string
          store_id: string
        }
        Update: {
          conversation_id?: string
          created_at?: string
          created_by?: string
          failure_reason?: string | null
          id?: string
          payload?: Json
          scheduled_for?: string
          status?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scheduled_sends_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "scheduled_sends_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      sdr_escalations: {
        Row: {
          assigned_at: string | null
          assigned_seller_id: string | null
          context_summary: Json
          conversation_id: string
          created_at: string
          customer_id: string | null
          first_human_response_at: string | null
          id: string
          lead_id: string | null
          mode: string
          reason: string
          reason_details: string | null
          session_id: string
          specialty_matched: boolean | null
          status: string
          store_id: string
          urgent_broadcast_at: string | null
          urgent_broadcast_claimed_at: string | null
          urgent_broadcast_claimed_by_seller_id: string | null
        }
        Insert: {
          assigned_at?: string | null
          assigned_seller_id?: string | null
          context_summary: Json
          conversation_id: string
          created_at?: string
          customer_id?: string | null
          first_human_response_at?: string | null
          id?: string
          lead_id?: string | null
          mode: string
          reason: string
          reason_details?: string | null
          session_id: string
          specialty_matched?: boolean | null
          status: string
          store_id: string
          urgent_broadcast_at?: string | null
          urgent_broadcast_claimed_at?: string | null
          urgent_broadcast_claimed_by_seller_id?: string | null
        }
        Update: {
          assigned_at?: string | null
          assigned_seller_id?: string | null
          context_summary?: Json
          conversation_id?: string
          created_at?: string
          customer_id?: string | null
          first_human_response_at?: string | null
          id?: string
          lead_id?: string | null
          mode?: string
          reason?: string
          reason_details?: string | null
          session_id?: string
          specialty_matched?: boolean | null
          status?: string
          store_id?: string
          urgent_broadcast_at?: string | null
          urgent_broadcast_claimed_at?: string | null
          urgent_broadcast_claimed_by_seller_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sdr_escalations_assigned_seller_id_fkey"
            columns: ["assigned_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sdr_escalations_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sdr_escalations_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sdr_escalations_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sdr_escalations_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sdr_escalations_urgent_broadcast_claimed_by_seller_id_fkey"
            columns: ["urgent_broadcast_claimed_by_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      sdr_sessions: {
        Row: {
          collected_data: Json
          conversation_id: string
          finish_reason: string | null
          finished_at: string | null
          id: string
          last_activity_at: string
          paused_from_state: string | null
          started_at: string
          state: string
        }
        Insert: {
          collected_data?: Json
          conversation_id: string
          finish_reason?: string | null
          finished_at?: string | null
          id?: string
          last_activity_at: string
          paused_from_state?: string | null
          started_at: string
          state: string
        }
        Update: {
          collected_data?: Json
          conversation_id?: string
          finish_reason?: string | null
          finished_at?: string | null
          id?: string
          last_activity_at?: string
          paused_from_state?: string | null
          started_at?: string
          state?: string
        }
        Relationships: [
          {
            foreignKeyName: "sdr_sessions_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      sellers: {
        Row: {
          active: boolean
          auth_user_id: string | null
          availability: string
          commission_rule: Json | null
          commission_tier: string | null
          created_at: string
          divisions: string[]
          email: string
          full_name: string
          id: string
          parent_seller_id: string | null
          phone: string | null
          region: string | null
          store_id: string
          theme_preference: Json | null
          type: string
          updated_at: string
          vehicle_cadastro_mode: string | null
        }
        Insert: {
          active?: boolean
          auth_user_id?: string | null
          availability?: string
          commission_rule?: Json | null
          commission_tier?: string | null
          created_at?: string
          divisions?: string[]
          email: string
          full_name: string
          id?: string
          parent_seller_id?: string | null
          phone?: string | null
          region?: string | null
          store_id: string
          theme_preference?: Json | null
          type: string
          updated_at?: string
          vehicle_cadastro_mode?: string | null
        }
        Update: {
          active?: boolean
          auth_user_id?: string | null
          availability?: string
          commission_rule?: Json | null
          commission_tier?: string | null
          created_at?: string
          divisions?: string[]
          email?: string
          full_name?: string
          id?: string
          parent_seller_id?: string | null
          phone?: string | null
          region?: string | null
          store_id?: string
          theme_preference?: Json | null
          type?: string
          updated_at?: string
          vehicle_cadastro_mode?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sellers_parent_seller_id_fkey"
            columns: ["parent_seller_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sellers_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      stores: {
        Row: {
          active_divisions: string[]
          address: string
          cnpj: string
          created_at: string
          id: string
          manager_id: string | null
          name: string
          settings: Json
          type: string
        }
        Insert: {
          active_divisions?: string[]
          address: string
          cnpj: string
          created_at: string
          id?: string
          manager_id?: string | null
          name: string
          settings: Json
          type: string
        }
        Update: {
          active_divisions?: string[]
          address?: string
          cnpj?: string
          created_at?: string
          id?: string
          manager_id?: string | null
          name?: string
          settings?: Json
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "stores_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "sellers"
            referencedColumns: ["id"]
          },
        ]
      }
      trackable_links: {
        Row: {
          asset_id: string | null
          conversation_id: string | null
          created_at: string
          created_by: string
          id: string
          last_opened_at: string | null
          lead_id: string | null
          opens: number
          short_ref: string
          store_id: string
          target_url: string
          utm: Json | null
        }
        Insert: {
          asset_id?: string | null
          conversation_id?: string | null
          created_at?: string
          created_by: string
          id?: string
          last_opened_at?: string | null
          lead_id?: string | null
          opens?: number
          short_ref: string
          store_id: string
          target_url: string
          utm?: Json | null
        }
        Update: {
          asset_id?: string | null
          conversation_id?: string | null
          created_at?: string
          created_by?: string
          id?: string
          last_opened_at?: string | null
          lead_id?: string | null
          opens?: number
          short_ref?: string
          store_id?: string
          target_url?: string
          utm?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "trackable_links_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trackable_links_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "trackable_links_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicle_models: {
        Row: {
          brand: string
          created_at: string
          created_by: string
          engine: string
          id: string
          model: string
          status: string
          updated_at: string
          updated_by: string | null
          year_end: number | null
          year_start: number | null
        }
        Insert: {
          brand: string
          created_at?: string
          created_by: string
          engine: string
          id?: string
          model: string
          status?: string
          updated_at?: string
          updated_by?: string | null
          year_end?: number | null
          year_start?: number | null
        }
        Update: {
          brand?: string
          created_at?: string
          created_by?: string
          engine?: string
          id?: string
          model?: string
          status?: string
          updated_at?: string
          updated_by?: string | null
          year_end?: number | null
          year_start?: number | null
        }
        Relationships: []
      }
      vehicles: {
        Row: {
          brand: string
          cadastro_status: string
          created_at: string
          current_km: number | null
          customer_id: string
          engine: string
          id: string
          model: string
          model_id: string | null
          plate: string | null
          service_history: Json
          vin: string | null
          year: number
        }
        Insert: {
          brand: string
          cadastro_status: string
          created_at?: string
          current_km?: number | null
          customer_id: string
          engine: string
          id?: string
          model: string
          model_id?: string | null
          plate?: string | null
          service_history?: Json
          vin?: string | null
          year: number
        }
        Update: {
          brand?: string
          cadastro_status?: string
          created_at?: string
          current_km?: number | null
          customer_id?: string
          engine?: string
          id?: string
          model?: string
          model_id?: string | null
          plate?: string | null
          service_history?: Json
          vin?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
        ]
      }
      whatsapp_accounts: {
        Row: {
          capabilities: Json
          created_at: string
          credentials_ref: string
          id: string
          label: string
          phone_number: string
          provider: string
          status: string
          store_id: string
        }
        Insert: {
          capabilities?: Json
          created_at?: string
          credentials_ref: string
          id?: string
          label: string
          phone_number: string
          provider: string
          status: string
          store_id: string
        }
        Update: {
          capabilities?: Json
          created_at?: string
          credentials_ref?: string
          id?: string
          label?: string
          phone_number?: string
          provider?: string
          status?: string
          store_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "whatsapp_accounts_store_id_fkey"
            columns: ["store_id"]
            isOneToOne: false
            referencedRelation: "stores"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_app_role: { Args: never; Returns: string }
      current_seller_id: { Args: never; Returns: string }
      current_store_id: { Args: never; Returns: string }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      is_staff: { Args: never; Returns: boolean }
      reconcile_derived_notifications: { Args: never; Returns: undefined }
      storefront_config: { Args: { p_store_id: string }; Returns: Json }
      storefront_top_selling: {
        Args: { p_limit?: number; p_store_id: string }
        Returns: {
          part_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
