/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as ErroRouteImport } from './routes/erro'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaIndexRouteImport } from './routes/loja.index'
import { Route as LojaContaRouteImport } from './routes/loja.conta'
import { Route as LojaCheckoutRouteImport } from './routes/loja.checkout'
import { Route as LojaCarrinhoRouteImport } from './routes/loja.carrinho'
import { Route as LojaBuscaRouteImport } from './routes/loja.busca'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppVeiculosRouteImport } from './routes/app.veiculos'
import { Route as AppSdrRouteImport } from './routes/app.sdr'
import { Route as AppPedidosRouteImport } from './routes/app.pedidos'
import { Route as AppOrcamentosRouteImport } from './routes/app.orcamentos'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCatalogoRouteImport } from './routes/app.catalogo'
import { Route as AppCarteiraRouteImport } from './routes/app.carteira'
import { Route as AppAtendimentoRouteImport } from './routes/app.atendimento'
import { Route as AppVeiculosIndexRouteImport } from './routes/app.veiculos.index'
import { Route as AppOrcamentosIndexRouteImport } from './routes/app.orcamentos.index'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppGestaoIndexRouteImport } from './routes/app.gestao.index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppClientesIndexRouteImport } from './routes/app.clientes.index'
import { Route as AppCatalogoIndexRouteImport } from './routes/app.catalogo.index'
import { Route as AppAtendimentoIndexRouteImport } from './routes/app.atendimento.index'
import { Route as LojaProdutoSlugRouteImport } from './routes/loja.produto.$slug'
import { Route as LojaContaPedidosRouteImport } from './routes/loja.conta.pedidos'
import { Route as LojaCategoriaSlugRouteImport } from './routes/loja.categoria.$slug'
import { Route as AppVeiculosIdRouteImport } from './routes/app.veiculos.$id'
import { Route as AppOrcamentosNovoRouteImport } from './routes/app.orcamentos.novo'
import { Route as AppOrcamentosIdRouteImport } from './routes/app.orcamentos.$id'
import { Route as AppLeadsIdRouteImport } from './routes/app.leads.$id'
import { Route as AppGestaoVendasRouteImport } from './routes/app.gestao.vendas'
import { Route as AppGestaoRentabilidadeRouteImport } from './routes/app.gestao.rentabilidade'
import { Route as AppGestaoRankingRouteImport } from './routes/app.gestao.ranking'
import { Route as AppGestaoPositivacaoRouteImport } from './routes/app.gestao.positivacao'
import { Route as AppGestaoMetasRouteImport } from './routes/app.gestao.metas'
import { Route as AppGestaoEstoqueRouteImport } from './routes/app.gestao.estoque'
import { Route as AppGestaoDreRouteImport } from './routes/app.gestao.dre'
import { Route as AppGestaoDespesasRouteImport } from './routes/app.gestao.despesas'
import { Route as AppGestaoComissoesRouteImport } from './routes/app.gestao.comissoes'
import { Route as AppGestaoCaixaRouteImport } from './routes/app.gestao.caixa'
import { Route as AppGestaoAbcRouteImport } from './routes/app.gestao.abc'
import { Route as AppConfiguracoesWhatsappRouteImport } from './routes/app.configuracoes.whatsapp'
import { Route as AppConfiguracoesUsuariosRouteImport } from './routes/app.configuracoes.usuarios'
import { Route as AppConfiguracoesPortalClienteRouteImport } from './routes/app.configuracoes.portal-cliente'
import { Route as AppConfiguracoesPerfilRouteImport } from './routes/app.configuracoes.perfil'
import { Route as AppConfiguracoesPapeisRouteImport } from './routes/app.configuracoes.papeis'
import { Route as AppConfiguracoesLojasRouteImport } from './routes/app.configuracoes.lojas'
import { Route as AppConfiguracoesGamificacaoRouteImport } from './routes/app.configuracoes.gamificacao'
import { Route as AppConfiguracoesDivisoesRouteImport } from './routes/app.configuracoes.divisoes'
import { Route as AppConfiguracoesDistribuicaoRouteImport } from './routes/app.configuracoes.distribuicao'
import { Route as AppConfiguracoesAuditoriaRouteImport } from './routes/app.configuracoes.auditoria'
import { Route as AppConfiguracoesAparenciaRouteImport } from './routes/app.configuracoes.aparencia'
import { Route as AppClientesIdRouteImport } from './routes/app.clientes.$id'
import { Route as AppCatalogoNovoRouteImport } from './routes/app.catalogo.novo'
import { Route as AppCatalogoIdRouteImport } from './routes/app.catalogo.$id'
import { Route as AppAtendimentoIdRouteImport } from './routes/app.atendimento.$id'
import { Route as AppConfiguracoesVeiculosCadastroModeRouteImport } from './routes/app.configuracoes.veiculos.cadastro-mode'
import { Route as AppConfiguracoesSdrTemplatesRouteImport } from './routes/app.configuracoes.sdr.templates'
import { Route as AppConfiguracoesSdrSimuladorRouteImport } from './routes/app.configuracoes.sdr.simulador'
import { Route as AppConfiguracoesSdrOrcamentoRouteImport } from './routes/app.configuracoes.sdr.orcamento'
import { Route as AppConfiguracoesAtendimentoTagsRouteImport } from './routes/app.configuracoes.atendimento.tags'
import { Route as AppConfiguracoesAtendimentoPipelineRouteImport } from './routes/app.configuracoes.atendimento.pipeline'
import { Route as AppConfiguracoesAtendimentoMotivosPerdaRouteImport } from './routes/app.configuracoes.atendimento.motivos-perda'
import { Route as AppConfiguracoesAtendimentoLifecycleRouteImport } from './routes/app.configuracoes.atendimento.lifecycle'
import { Route as AppConfiguracoesAtendimentoHorarioComercialRouteImport } from './routes/app.configuracoes.atendimento.horario-comercial'
import { Route as AppCatalogoIdEditarRouteImport } from './routes/app.catalogo.$id.editar'

const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ErroRoute = ErroRouteImport.update({
  id: '/erro',
  path: '/erro',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaIndexRoute = LojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaRoute,
} as any)
const LojaContaRoute = LojaContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => LojaRoute,
} as any)
const LojaCheckoutRoute = LojaCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LojaRoute,
} as any)
const LojaCarrinhoRoute = LojaCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => LojaRoute,
} as any)
const LojaBuscaRoute = LojaBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => LojaRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppSdrRoute = AppSdrRouteImport.update({
  id: '/sdr',
  path: '/sdr',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteiraRoute = AppCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVeiculosRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrcamentosRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppGestaoIndexRoute = AppGestaoIndexRouteImport.update({
  id: '/gestao/',
  path: '/gestao/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppCatalogoIndexRoute = AppCatalogoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCatalogoRoute,
} as any)
const AppAtendimentoIndexRoute = AppAtendimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAtendimentoRoute,
} as any)
const LojaProdutoSlugRoute = LojaProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LojaRoute,
} as any)
const LojaContaPedidosRoute = LojaContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => LojaContaRoute,
} as any)
const LojaCategoriaSlugRoute = LojaCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => LojaRoute,
} as any)
const AppVeiculosIdRoute = AppVeiculosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVeiculosRoute,
} as any)
const AppOrcamentosNovoRoute = AppOrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppOrcamentosRoute,
} as any)
const AppOrcamentosIdRoute = AppOrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrcamentosRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppGestaoVendasRoute = AppGestaoVendasRouteImport.update({
  id: '/gestao/vendas',
  path: '/gestao/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRentabilidadeRoute = AppGestaoRentabilidadeRouteImport.update({
  id: '/gestao/rentabilidade',
  path: '/gestao/rentabilidade',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoRankingRoute = AppGestaoRankingRouteImport.update({
  id: '/gestao/ranking',
  path: '/gestao/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoPositivacaoRoute = AppGestaoPositivacaoRouteImport.update({
  id: '/gestao/positivacao',
  path: '/gestao/positivacao',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoMetasRoute = AppGestaoMetasRouteImport.update({
  id: '/gestao/metas',
  path: '/gestao/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoEstoqueRoute = AppGestaoEstoqueRouteImport.update({
  id: '/gestao/estoque',
  path: '/gestao/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoDreRoute = AppGestaoDreRouteImport.update({
  id: '/gestao/dre',
  path: '/gestao/dre',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoDespesasRoute = AppGestaoDespesasRouteImport.update({
  id: '/gestao/despesas',
  path: '/gestao/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoComissoesRoute = AppGestaoComissoesRouteImport.update({
  id: '/gestao/comissoes',
  path: '/gestao/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoCaixaRoute = AppGestaoCaixaRouteImport.update({
  id: '/gestao/caixa',
  path: '/gestao/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppGestaoAbcRoute = AppGestaoAbcRouteImport.update({
  id: '/gestao/abc',
  path: '/gestao/abc',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesWhatsappRoute =
  AppConfiguracoesWhatsappRouteImport.update({
    id: '/configuracoes/whatsapp',
    path: '/configuracoes/whatsapp',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesUsuariosRoute =
  AppConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesPortalClienteRoute =
  AppConfiguracoesPortalClienteRouteImport.update({
    id: '/configuracoes/portal-cliente',
    path: '/configuracoes/portal-cliente',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesPerfilRoute = AppConfiguracoesPerfilRouteImport.update({
  id: '/configuracoes/perfil',
  path: '/configuracoes/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesPapeisRoute = AppConfiguracoesPapeisRouteImport.update({
  id: '/configuracoes/papeis',
  path: '/configuracoes/papeis',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesLojasRoute = AppConfiguracoesLojasRouteImport.update({
  id: '/configuracoes/lojas',
  path: '/configuracoes/lojas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesGamificacaoRoute =
  AppConfiguracoesGamificacaoRouteImport.update({
    id: '/configuracoes/gamificacao',
    path: '/configuracoes/gamificacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesDivisoesRoute =
  AppConfiguracoesDivisoesRouteImport.update({
    id: '/configuracoes/divisoes',
    path: '/configuracoes/divisoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesDistribuicaoRoute =
  AppConfiguracoesDistribuicaoRouteImport.update({
    id: '/configuracoes/distribuicao',
    path: '/configuracoes/distribuicao',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAuditoriaRoute =
  AppConfiguracoesAuditoriaRouteImport.update({
    id: '/configuracoes/auditoria',
    path: '/configuracoes/auditoria',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAparenciaRoute =
  AppConfiguracoesAparenciaRouteImport.update({
    id: '/configuracoes/aparencia',
    path: '/configuracoes/aparencia',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppCatalogoNovoRoute = AppCatalogoNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppCatalogoRoute,
} as any)
const AppCatalogoIdRoute = AppCatalogoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCatalogoRoute,
} as any)
const AppAtendimentoIdRoute = AppAtendimentoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAtendimentoRoute,
} as any)
const AppConfiguracoesVeiculosCadastroModeRoute =
  AppConfiguracoesVeiculosCadastroModeRouteImport.update({
    id: '/configuracoes/veiculos/cadastro-mode',
    path: '/configuracoes/veiculos/cadastro-mode',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesSdrTemplatesRoute =
  AppConfiguracoesSdrTemplatesRouteImport.update({
    id: '/configuracoes/sdr/templates',
    path: '/configuracoes/sdr/templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesSdrSimuladorRoute =
  AppConfiguracoesSdrSimuladorRouteImport.update({
    id: '/configuracoes/sdr/simulador',
    path: '/configuracoes/sdr/simulador',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesSdrOrcamentoRoute =
  AppConfiguracoesSdrOrcamentoRouteImport.update({
    id: '/configuracoes/sdr/orcamento',
    path: '/configuracoes/sdr/orcamento',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAtendimentoTagsRoute =
  AppConfiguracoesAtendimentoTagsRouteImport.update({
    id: '/configuracoes/atendimento/tags',
    path: '/configuracoes/atendimento/tags',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAtendimentoPipelineRoute =
  AppConfiguracoesAtendimentoPipelineRouteImport.update({
    id: '/configuracoes/atendimento/pipeline',
    path: '/configuracoes/atendimento/pipeline',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAtendimentoMotivosPerdaRoute =
  AppConfiguracoesAtendimentoMotivosPerdaRouteImport.update({
    id: '/configuracoes/atendimento/motivos-perda',
    path: '/configuracoes/atendimento/motivos-perda',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAtendimentoLifecycleRoute =
  AppConfiguracoesAtendimentoLifecycleRouteImport.update({
    id: '/configuracoes/atendimento/lifecycle',
    path: '/configuracoes/atendimento/lifecycle',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesAtendimentoHorarioComercialRoute =
  AppConfiguracoesAtendimentoHorarioComercialRouteImport.update({
    id: '/configuracoes/atendimento/horario-comercial',
    path: '/configuracoes/atendimento/horario-comercial',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogoIdEditarRoute = AppCatalogoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AppCatalogoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/erro': typeof ErroRoute
  '/loja': typeof LojaRouteWithChildren
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/app/atendimento': typeof AppAtendimentoRouteWithChildren
  '/app/carteira': typeof AppCarteiraRoute
  '/app/catalogo': typeof AppCatalogoRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/inicio': typeof AppInicioRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/orcamentos': typeof AppOrcamentosRouteWithChildren
  '/app/pedidos': typeof AppPedidosRoute
  '/app/sdr': typeof AppSdrRoute
  '/app/veiculos': typeof AppVeiculosRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/conta': typeof LojaContaRouteWithChildren
  '/loja/': typeof LojaIndexRoute
  '/app/atendimento/$id': typeof AppAtendimentoIdRoute
  '/app/catalogo/$id': typeof AppCatalogoIdRouteWithChildren
  '/app/catalogo/novo': typeof AppCatalogoNovoRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/configuracoes/aparencia': typeof AppConfiguracoesAparenciaRoute
  '/app/configuracoes/auditoria': typeof AppConfiguracoesAuditoriaRoute
  '/app/configuracoes/distribuicao': typeof AppConfiguracoesDistribuicaoRoute
  '/app/configuracoes/divisoes': typeof AppConfiguracoesDivisoesRoute
  '/app/configuracoes/gamificacao': typeof AppConfiguracoesGamificacaoRoute
  '/app/configuracoes/lojas': typeof AppConfiguracoesLojasRoute
  '/app/configuracoes/papeis': typeof AppConfiguracoesPapeisRoute
  '/app/configuracoes/perfil': typeof AppConfiguracoesPerfilRoute
  '/app/configuracoes/portal-cliente': typeof AppConfiguracoesPortalClienteRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/app/configuracoes/whatsapp': typeof AppConfiguracoesWhatsappRoute
  '/app/gestao/abc': typeof AppGestaoAbcRoute
  '/app/gestao/caixa': typeof AppGestaoCaixaRoute
  '/app/gestao/comissoes': typeof AppGestaoComissoesRoute
  '/app/gestao/despesas': typeof AppGestaoDespesasRoute
  '/app/gestao/dre': typeof AppGestaoDreRoute
  '/app/gestao/estoque': typeof AppGestaoEstoqueRoute
  '/app/gestao/metas': typeof AppGestaoMetasRoute
  '/app/gestao/positivacao': typeof AppGestaoPositivacaoRoute
  '/app/gestao/ranking': typeof AppGestaoRankingRoute
  '/app/gestao/rentabilidade': typeof AppGestaoRentabilidadeRoute
  '/app/gestao/vendas': typeof AppGestaoVendasRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/loja/categoria/$slug': typeof LojaCategoriaSlugRoute
  '/loja/conta/pedidos': typeof LojaContaPedidosRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/app/atendimento/': typeof AppAtendimentoIndexRoute
  '/app/catalogo/': typeof AppCatalogoIndexRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/gestao/': typeof AppGestaoIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/catalogo/$id/editar': typeof AppCatalogoIdEditarRoute
  '/app/configuracoes/atendimento/horario-comercial': typeof AppConfiguracoesAtendimentoHorarioComercialRoute
  '/app/configuracoes/atendimento/lifecycle': typeof AppConfiguracoesAtendimentoLifecycleRoute
  '/app/configuracoes/atendimento/motivos-perda': typeof AppConfiguracoesAtendimentoMotivosPerdaRoute
  '/app/configuracoes/atendimento/pipeline': typeof AppConfiguracoesAtendimentoPipelineRoute
  '/app/configuracoes/atendimento/tags': typeof AppConfiguracoesAtendimentoTagsRoute
  '/app/configuracoes/sdr/orcamento': typeof AppConfiguracoesSdrOrcamentoRoute
  '/app/configuracoes/sdr/simulador': typeof AppConfiguracoesSdrSimuladorRoute
  '/app/configuracoes/sdr/templates': typeof AppConfiguracoesSdrTemplatesRoute
  '/app/configuracoes/veiculos/cadastro-mode': typeof AppConfiguracoesVeiculosCadastroModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/erro': typeof ErroRoute
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/app/carteira': typeof AppCarteiraRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/pedidos': typeof AppPedidosRoute
  '/app/sdr': typeof AppSdrRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/conta': typeof LojaContaRouteWithChildren
  '/loja': typeof LojaIndexRoute
  '/app/atendimento/$id': typeof AppAtendimentoIdRoute
  '/app/catalogo/$id': typeof AppCatalogoIdRouteWithChildren
  '/app/catalogo/novo': typeof AppCatalogoNovoRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/configuracoes/aparencia': typeof AppConfiguracoesAparenciaRoute
  '/app/configuracoes/auditoria': typeof AppConfiguracoesAuditoriaRoute
  '/app/configuracoes/distribuicao': typeof AppConfiguracoesDistribuicaoRoute
  '/app/configuracoes/divisoes': typeof AppConfiguracoesDivisoesRoute
  '/app/configuracoes/gamificacao': typeof AppConfiguracoesGamificacaoRoute
  '/app/configuracoes/lojas': typeof AppConfiguracoesLojasRoute
  '/app/configuracoes/papeis': typeof AppConfiguracoesPapeisRoute
  '/app/configuracoes/perfil': typeof AppConfiguracoesPerfilRoute
  '/app/configuracoes/portal-cliente': typeof AppConfiguracoesPortalClienteRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/app/configuracoes/whatsapp': typeof AppConfiguracoesWhatsappRoute
  '/app/gestao/abc': typeof AppGestaoAbcRoute
  '/app/gestao/caixa': typeof AppGestaoCaixaRoute
  '/app/gestao/comissoes': typeof AppGestaoComissoesRoute
  '/app/gestao/despesas': typeof AppGestaoDespesasRoute
  '/app/gestao/dre': typeof AppGestaoDreRoute
  '/app/gestao/estoque': typeof AppGestaoEstoqueRoute
  '/app/gestao/metas': typeof AppGestaoMetasRoute
  '/app/gestao/positivacao': typeof AppGestaoPositivacaoRoute
  '/app/gestao/ranking': typeof AppGestaoRankingRoute
  '/app/gestao/rentabilidade': typeof AppGestaoRentabilidadeRoute
  '/app/gestao/vendas': typeof AppGestaoVendasRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/loja/categoria/$slug': typeof LojaCategoriaSlugRoute
  '/loja/conta/pedidos': typeof LojaContaPedidosRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/app/atendimento': typeof AppAtendimentoIndexRoute
  '/app/catalogo': typeof AppCatalogoIndexRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/gestao': typeof AppGestaoIndexRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/orcamentos': typeof AppOrcamentosIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
  '/app/catalogo/$id/editar': typeof AppCatalogoIdEditarRoute
  '/app/configuracoes/atendimento/horario-comercial': typeof AppConfiguracoesAtendimentoHorarioComercialRoute
  '/app/configuracoes/atendimento/lifecycle': typeof AppConfiguracoesAtendimentoLifecycleRoute
  '/app/configuracoes/atendimento/motivos-perda': typeof AppConfiguracoesAtendimentoMotivosPerdaRoute
  '/app/configuracoes/atendimento/pipeline': typeof AppConfiguracoesAtendimentoPipelineRoute
  '/app/configuracoes/atendimento/tags': typeof AppConfiguracoesAtendimentoTagsRoute
  '/app/configuracoes/sdr/orcamento': typeof AppConfiguracoesSdrOrcamentoRoute
  '/app/configuracoes/sdr/simulador': typeof AppConfiguracoesSdrSimuladorRoute
  '/app/configuracoes/sdr/templates': typeof AppConfiguracoesSdrTemplatesRoute
  '/app/configuracoes/veiculos/cadastro-mode': typeof AppConfiguracoesVeiculosCadastroModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/erro': typeof ErroRoute
  '/loja': typeof LojaRouteWithChildren
  '/portal': typeof PortalRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/app/atendimento': typeof AppAtendimentoRouteWithChildren
  '/app/carteira': typeof AppCarteiraRoute
  '/app/catalogo': typeof AppCatalogoRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/inicio': typeof AppInicioRoute
  '/app/leads': typeof AppLeadsRouteWithChildren
  '/app/orcamentos': typeof AppOrcamentosRouteWithChildren
  '/app/pedidos': typeof AppPedidosRoute
  '/app/sdr': typeof AppSdrRoute
  '/app/veiculos': typeof AppVeiculosRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/loja/busca': typeof LojaBuscaRoute
  '/loja/carrinho': typeof LojaCarrinhoRoute
  '/loja/checkout': typeof LojaCheckoutRoute
  '/loja/conta': typeof LojaContaRouteWithChildren
  '/loja/': typeof LojaIndexRoute
  '/app/atendimento/$id': typeof AppAtendimentoIdRoute
  '/app/catalogo/$id': typeof AppCatalogoIdRouteWithChildren
  '/app/catalogo/novo': typeof AppCatalogoNovoRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/configuracoes/aparencia': typeof AppConfiguracoesAparenciaRoute
  '/app/configuracoes/auditoria': typeof AppConfiguracoesAuditoriaRoute
  '/app/configuracoes/distribuicao': typeof AppConfiguracoesDistribuicaoRoute
  '/app/configuracoes/divisoes': typeof AppConfiguracoesDivisoesRoute
  '/app/configuracoes/gamificacao': typeof AppConfiguracoesGamificacaoRoute
  '/app/configuracoes/lojas': typeof AppConfiguracoesLojasRoute
  '/app/configuracoes/papeis': typeof AppConfiguracoesPapeisRoute
  '/app/configuracoes/perfil': typeof AppConfiguracoesPerfilRoute
  '/app/configuracoes/portal-cliente': typeof AppConfiguracoesPortalClienteRoute
  '/app/configuracoes/usuarios': typeof AppConfiguracoesUsuariosRoute
  '/app/configuracoes/whatsapp': typeof AppConfiguracoesWhatsappRoute
  '/app/gestao/abc': typeof AppGestaoAbcRoute
  '/app/gestao/caixa': typeof AppGestaoCaixaRoute
  '/app/gestao/comissoes': typeof AppGestaoComissoesRoute
  '/app/gestao/despesas': typeof AppGestaoDespesasRoute
  '/app/gestao/dre': typeof AppGestaoDreRoute
  '/app/gestao/estoque': typeof AppGestaoEstoqueRoute
  '/app/gestao/metas': typeof AppGestaoMetasRoute
  '/app/gestao/positivacao': typeof AppGestaoPositivacaoRoute
  '/app/gestao/ranking': typeof AppGestaoRankingRoute
  '/app/gestao/rentabilidade': typeof AppGestaoRentabilidadeRoute
  '/app/gestao/vendas': typeof AppGestaoVendasRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/loja/categoria/$slug': typeof LojaCategoriaSlugRoute
  '/loja/conta/pedidos': typeof LojaContaPedidosRoute
  '/loja/produto/$slug': typeof LojaProdutoSlugRoute
  '/app/atendimento/': typeof AppAtendimentoIndexRoute
  '/app/catalogo/': typeof AppCatalogoIndexRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/gestao/': typeof AppGestaoIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/catalogo/$id/editar': typeof AppCatalogoIdEditarRoute
  '/app/configuracoes/atendimento/horario-comercial': typeof AppConfiguracoesAtendimentoHorarioComercialRoute
  '/app/configuracoes/atendimento/lifecycle': typeof AppConfiguracoesAtendimentoLifecycleRoute
  '/app/configuracoes/atendimento/motivos-perda': typeof AppConfiguracoesAtendimentoMotivosPerdaRoute
  '/app/configuracoes/atendimento/pipeline': typeof AppConfiguracoesAtendimentoPipelineRoute
  '/app/configuracoes/atendimento/tags': typeof AppConfiguracoesAtendimentoTagsRoute
  '/app/configuracoes/sdr/orcamento': typeof AppConfiguracoesSdrOrcamentoRoute
  '/app/configuracoes/sdr/simulador': typeof AppConfiguracoesSdrSimuladorRoute
  '/app/configuracoes/sdr/templates': typeof AppConfiguracoesSdrTemplatesRoute
  '/app/configuracoes/veiculos/cadastro-mode': typeof AppConfiguracoesVeiculosCadastroModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/design-system'
    | '/erro'
    | '/loja'
    | '/portal'
    | '/sem-permissao'
    | '/app/atendimento'
    | '/app/carteira'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/inicio'
    | '/app/leads'
    | '/app/orcamentos'
    | '/app/pedidos'
    | '/app/sdr'
    | '/app/veiculos'
    | '/auth/login'
    | '/auth/logout'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/conta'
    | '/loja/'
    | '/app/atendimento/$id'
    | '/app/catalogo/$id'
    | '/app/catalogo/novo'
    | '/app/clientes/$id'
    | '/app/configuracoes/aparencia'
    | '/app/configuracoes/auditoria'
    | '/app/configuracoes/distribuicao'
    | '/app/configuracoes/divisoes'
    | '/app/configuracoes/gamificacao'
    | '/app/configuracoes/lojas'
    | '/app/configuracoes/papeis'
    | '/app/configuracoes/perfil'
    | '/app/configuracoes/portal-cliente'
    | '/app/configuracoes/usuarios'
    | '/app/configuracoes/whatsapp'
    | '/app/gestao/abc'
    | '/app/gestao/caixa'
    | '/app/gestao/comissoes'
    | '/app/gestao/despesas'
    | '/app/gestao/dre'
    | '/app/gestao/estoque'
    | '/app/gestao/metas'
    | '/app/gestao/positivacao'
    | '/app/gestao/ranking'
    | '/app/gestao/rentabilidade'
    | '/app/gestao/vendas'
    | '/app/leads/$id'
    | '/app/orcamentos/$id'
    | '/app/orcamentos/novo'
    | '/app/veiculos/$id'
    | '/loja/categoria/$slug'
    | '/loja/conta/pedidos'
    | '/loja/produto/$slug'
    | '/app/atendimento/'
    | '/app/catalogo/'
    | '/app/clientes/'
    | '/app/configuracoes/'
    | '/app/gestao/'
    | '/app/leads/'
    | '/app/orcamentos/'
    | '/app/veiculos/'
    | '/app/catalogo/$id/editar'
    | '/app/configuracoes/atendimento/horario-comercial'
    | '/app/configuracoes/atendimento/lifecycle'
    | '/app/configuracoes/atendimento/motivos-perda'
    | '/app/configuracoes/atendimento/pipeline'
    | '/app/configuracoes/atendimento/tags'
    | '/app/configuracoes/sdr/orcamento'
    | '/app/configuracoes/sdr/simulador'
    | '/app/configuracoes/sdr/templates'
    | '/app/configuracoes/veiculos/cadastro-mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/design-system'
    | '/erro'
    | '/portal'
    | '/sem-permissao'
    | '/app/carteira'
    | '/app/inicio'
    | '/app/pedidos'
    | '/app/sdr'
    | '/auth/login'
    | '/auth/logout'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/conta'
    | '/loja'
    | '/app/atendimento/$id'
    | '/app/catalogo/$id'
    | '/app/catalogo/novo'
    | '/app/clientes/$id'
    | '/app/configuracoes/aparencia'
    | '/app/configuracoes/auditoria'
    | '/app/configuracoes/distribuicao'
    | '/app/configuracoes/divisoes'
    | '/app/configuracoes/gamificacao'
    | '/app/configuracoes/lojas'
    | '/app/configuracoes/papeis'
    | '/app/configuracoes/perfil'
    | '/app/configuracoes/portal-cliente'
    | '/app/configuracoes/usuarios'
    | '/app/configuracoes/whatsapp'
    | '/app/gestao/abc'
    | '/app/gestao/caixa'
    | '/app/gestao/comissoes'
    | '/app/gestao/despesas'
    | '/app/gestao/dre'
    | '/app/gestao/estoque'
    | '/app/gestao/metas'
    | '/app/gestao/positivacao'
    | '/app/gestao/ranking'
    | '/app/gestao/rentabilidade'
    | '/app/gestao/vendas'
    | '/app/leads/$id'
    | '/app/orcamentos/$id'
    | '/app/orcamentos/novo'
    | '/app/veiculos/$id'
    | '/loja/categoria/$slug'
    | '/loja/conta/pedidos'
    | '/loja/produto/$slug'
    | '/app/atendimento'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/gestao'
    | '/app/leads'
    | '/app/orcamentos'
    | '/app/veiculos'
    | '/app/catalogo/$id/editar'
    | '/app/configuracoes/atendimento/horario-comercial'
    | '/app/configuracoes/atendimento/lifecycle'
    | '/app/configuracoes/atendimento/motivos-perda'
    | '/app/configuracoes/atendimento/pipeline'
    | '/app/configuracoes/atendimento/tags'
    | '/app/configuracoes/sdr/orcamento'
    | '/app/configuracoes/sdr/simulador'
    | '/app/configuracoes/sdr/templates'
    | '/app/configuracoes/veiculos/cadastro-mode'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/design-system'
    | '/erro'
    | '/loja'
    | '/portal'
    | '/sem-permissao'
    | '/app/atendimento'
    | '/app/carteira'
    | '/app/catalogo'
    | '/app/clientes'
    | '/app/inicio'
    | '/app/leads'
    | '/app/orcamentos'
    | '/app/pedidos'
    | '/app/sdr'
    | '/app/veiculos'
    | '/auth/login'
    | '/auth/logout'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/loja/conta'
    | '/loja/'
    | '/app/atendimento/$id'
    | '/app/catalogo/$id'
    | '/app/catalogo/novo'
    | '/app/clientes/$id'
    | '/app/configuracoes/aparencia'
    | '/app/configuracoes/auditoria'
    | '/app/configuracoes/distribuicao'
    | '/app/configuracoes/divisoes'
    | '/app/configuracoes/gamificacao'
    | '/app/configuracoes/lojas'
    | '/app/configuracoes/papeis'
    | '/app/configuracoes/perfil'
    | '/app/configuracoes/portal-cliente'
    | '/app/configuracoes/usuarios'
    | '/app/configuracoes/whatsapp'
    | '/app/gestao/abc'
    | '/app/gestao/caixa'
    | '/app/gestao/comissoes'
    | '/app/gestao/despesas'
    | '/app/gestao/dre'
    | '/app/gestao/estoque'
    | '/app/gestao/metas'
    | '/app/gestao/positivacao'
    | '/app/gestao/ranking'
    | '/app/gestao/rentabilidade'
    | '/app/gestao/vendas'
    | '/app/leads/$id'
    | '/app/orcamentos/$id'
    | '/app/orcamentos/novo'
    | '/app/veiculos/$id'
    | '/loja/categoria/$slug'
    | '/loja/conta/pedidos'
    | '/loja/produto/$slug'
    | '/app/atendimento/'
    | '/app/catalogo/'
    | '/app/clientes/'
    | '/app/configuracoes/'
    | '/app/gestao/'
    | '/app/leads/'
    | '/app/orcamentos/'
    | '/app/veiculos/'
    | '/app/catalogo/$id/editar'
    | '/app/configuracoes/atendimento/horario-comercial'
    | '/app/configuracoes/atendimento/lifecycle'
    | '/app/configuracoes/atendimento/motivos-perda'
    | '/app/configuracoes/atendimento/pipeline'
    | '/app/configuracoes/atendimento/tags'
    | '/app/configuracoes/sdr/orcamento'
    | '/app/configuracoes/sdr/simulador'
    | '/app/configuracoes/sdr/templates'
    | '/app/configuracoes/veiculos/cadastro-mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  ErroRoute: typeof ErroRoute
  LojaRoute: typeof LojaRouteWithChildren
  PortalRoute: typeof PortalRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erro': {
      id: '/erro'
      path: '/erro'
      fullPath: '/erro'
      preLoaderRoute: typeof ErroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/': {
      id: '/loja/'
      path: '/'
      fullPath: '/loja/'
      preLoaderRoute: typeof LojaIndexRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/conta': {
      id: '/loja/conta'
      path: '/conta'
      fullPath: '/loja/conta'
      preLoaderRoute: typeof LojaContaRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/checkout': {
      id: '/loja/checkout'
      path: '/checkout'
      fullPath: '/loja/checkout'
      preLoaderRoute: typeof LojaCheckoutRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/carrinho': {
      id: '/loja/carrinho'
      path: '/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof LojaCarrinhoRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/busca': {
      id: '/loja/busca'
      path: '/busca'
      fullPath: '/loja/busca'
      preLoaderRoute: typeof LojaBuscaRouteImport
      parentRoute: typeof LojaRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/veiculos': {
      id: '/app/veiculos'
      path: '/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sdr': {
      id: '/app/sdr'
      path: '/sdr'
      fullPath: '/app/sdr'
      preLoaderRoute: typeof AppSdrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pedidos': {
      id: '/app/pedidos'
      path: '/pedidos'
      fullPath: '/app/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamentos': {
      id: '/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo': {
      id: '/app/catalogo'
      path: '/catalogo'
      fullPath: '/app/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carteira': {
      id: '/app/carteira'
      path: '/carteira'
      fullPath: '/app/carteira'
      preLoaderRoute: typeof AppCarteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendimento': {
      id: '/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppVeiculosRoute
    }
    '/app/orcamentos/': {
      id: '/app/orcamentos/'
      path: '/'
      fullPath: '/app/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppOrcamentosRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/app/gestao/': {
      id: '/app/gestao/'
      path: '/gestao'
      fullPath: '/app/gestao/'
      preLoaderRoute: typeof AppGestaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/catalogo/': {
      id: '/app/catalogo/'
      path: '/'
      fullPath: '/app/catalogo/'
      preLoaderRoute: typeof AppCatalogoIndexRouteImport
      parentRoute: typeof AppCatalogoRoute
    }
    '/app/atendimento/': {
      id: '/app/atendimento/'
      path: '/'
      fullPath: '/app/atendimento/'
      preLoaderRoute: typeof AppAtendimentoIndexRouteImport
      parentRoute: typeof AppAtendimentoRoute
    }
    '/loja/produto/$slug': {
      id: '/loja/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/loja/produto/$slug'
      preLoaderRoute: typeof LojaProdutoSlugRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja/conta/pedidos': {
      id: '/loja/conta/pedidos'
      path: '/pedidos'
      fullPath: '/loja/conta/pedidos'
      preLoaderRoute: typeof LojaContaPedidosRouteImport
      parentRoute: typeof LojaContaRoute
    }
    '/loja/categoria/$slug': {
      id: '/loja/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/loja/categoria/$slug'
      preLoaderRoute: typeof LojaCategoriaSlugRouteImport
      parentRoute: typeof LojaRoute
    }
    '/app/veiculos/$id': {
      id: '/app/veiculos/$id'
      path: '/$id'
      fullPath: '/app/veiculos/$id'
      preLoaderRoute: typeof AppVeiculosIdRouteImport
      parentRoute: typeof AppVeiculosRoute
    }
    '/app/orcamentos/novo': {
      id: '/app/orcamentos/novo'
      path: '/novo'
      fullPath: '/app/orcamentos/novo'
      preLoaderRoute: typeof AppOrcamentosNovoRouteImport
      parentRoute: typeof AppOrcamentosRoute
    }
    '/app/orcamentos/$id': {
      id: '/app/orcamentos/$id'
      path: '/$id'
      fullPath: '/app/orcamentos/$id'
      preLoaderRoute: typeof AppOrcamentosIdRouteImport
      parentRoute: typeof AppOrcamentosRoute
    }
    '/app/leads/$id': {
      id: '/app/leads/$id'
      path: '/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/app/gestao/vendas': {
      id: '/app/gestao/vendas'
      path: '/gestao/vendas'
      fullPath: '/app/gestao/vendas'
      preLoaderRoute: typeof AppGestaoVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/rentabilidade': {
      id: '/app/gestao/rentabilidade'
      path: '/gestao/rentabilidade'
      fullPath: '/app/gestao/rentabilidade'
      preLoaderRoute: typeof AppGestaoRentabilidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/ranking': {
      id: '/app/gestao/ranking'
      path: '/gestao/ranking'
      fullPath: '/app/gestao/ranking'
      preLoaderRoute: typeof AppGestaoRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/positivacao': {
      id: '/app/gestao/positivacao'
      path: '/gestao/positivacao'
      fullPath: '/app/gestao/positivacao'
      preLoaderRoute: typeof AppGestaoPositivacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/metas': {
      id: '/app/gestao/metas'
      path: '/gestao/metas'
      fullPath: '/app/gestao/metas'
      preLoaderRoute: typeof AppGestaoMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/estoque': {
      id: '/app/gestao/estoque'
      path: '/gestao/estoque'
      fullPath: '/app/gestao/estoque'
      preLoaderRoute: typeof AppGestaoEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/dre': {
      id: '/app/gestao/dre'
      path: '/gestao/dre'
      fullPath: '/app/gestao/dre'
      preLoaderRoute: typeof AppGestaoDreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/despesas': {
      id: '/app/gestao/despesas'
      path: '/gestao/despesas'
      fullPath: '/app/gestao/despesas'
      preLoaderRoute: typeof AppGestaoDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/comissoes': {
      id: '/app/gestao/comissoes'
      path: '/gestao/comissoes'
      fullPath: '/app/gestao/comissoes'
      preLoaderRoute: typeof AppGestaoComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/caixa': {
      id: '/app/gestao/caixa'
      path: '/gestao/caixa'
      fullPath: '/app/gestao/caixa'
      preLoaderRoute: typeof AppGestaoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestao/abc': {
      id: '/app/gestao/abc'
      path: '/gestao/abc'
      fullPath: '/app/gestao/abc'
      preLoaderRoute: typeof AppGestaoAbcRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/whatsapp': {
      id: '/app/configuracoes/whatsapp'
      path: '/configuracoes/whatsapp'
      fullPath: '/app/configuracoes/whatsapp'
      preLoaderRoute: typeof AppConfiguracoesWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/usuarios': {
      id: '/app/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/app/configuracoes/usuarios'
      preLoaderRoute: typeof AppConfiguracoesUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/portal-cliente': {
      id: '/app/configuracoes/portal-cliente'
      path: '/configuracoes/portal-cliente'
      fullPath: '/app/configuracoes/portal-cliente'
      preLoaderRoute: typeof AppConfiguracoesPortalClienteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/perfil': {
      id: '/app/configuracoes/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/app/configuracoes/perfil'
      preLoaderRoute: typeof AppConfiguracoesPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/papeis': {
      id: '/app/configuracoes/papeis'
      path: '/configuracoes/papeis'
      fullPath: '/app/configuracoes/papeis'
      preLoaderRoute: typeof AppConfiguracoesPapeisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/lojas': {
      id: '/app/configuracoes/lojas'
      path: '/configuracoes/lojas'
      fullPath: '/app/configuracoes/lojas'
      preLoaderRoute: typeof AppConfiguracoesLojasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/gamificacao': {
      id: '/app/configuracoes/gamificacao'
      path: '/configuracoes/gamificacao'
      fullPath: '/app/configuracoes/gamificacao'
      preLoaderRoute: typeof AppConfiguracoesGamificacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/divisoes': {
      id: '/app/configuracoes/divisoes'
      path: '/configuracoes/divisoes'
      fullPath: '/app/configuracoes/divisoes'
      preLoaderRoute: typeof AppConfiguracoesDivisoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/distribuicao': {
      id: '/app/configuracoes/distribuicao'
      path: '/configuracoes/distribuicao'
      fullPath: '/app/configuracoes/distribuicao'
      preLoaderRoute: typeof AppConfiguracoesDistribuicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/auditoria': {
      id: '/app/configuracoes/auditoria'
      path: '/configuracoes/auditoria'
      fullPath: '/app/configuracoes/auditoria'
      preLoaderRoute: typeof AppConfiguracoesAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/aparencia': {
      id: '/app/configuracoes/aparencia'
      path: '/configuracoes/aparencia'
      fullPath: '/app/configuracoes/aparencia'
      preLoaderRoute: typeof AppConfiguracoesAparenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/catalogo/novo': {
      id: '/app/catalogo/novo'
      path: '/novo'
      fullPath: '/app/catalogo/novo'
      preLoaderRoute: typeof AppCatalogoNovoRouteImport
      parentRoute: typeof AppCatalogoRoute
    }
    '/app/catalogo/$id': {
      id: '/app/catalogo/$id'
      path: '/$id'
      fullPath: '/app/catalogo/$id'
      preLoaderRoute: typeof AppCatalogoIdRouteImport
      parentRoute: typeof AppCatalogoRoute
    }
    '/app/atendimento/$id': {
      id: '/app/atendimento/$id'
      path: '/$id'
      fullPath: '/app/atendimento/$id'
      preLoaderRoute: typeof AppAtendimentoIdRouteImport
      parentRoute: typeof AppAtendimentoRoute
    }
    '/app/configuracoes/veiculos/cadastro-mode': {
      id: '/app/configuracoes/veiculos/cadastro-mode'
      path: '/configuracoes/veiculos/cadastro-mode'
      fullPath: '/app/configuracoes/veiculos/cadastro-mode'
      preLoaderRoute: typeof AppConfiguracoesVeiculosCadastroModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/sdr/templates': {
      id: '/app/configuracoes/sdr/templates'
      path: '/configuracoes/sdr/templates'
      fullPath: '/app/configuracoes/sdr/templates'
      preLoaderRoute: typeof AppConfiguracoesSdrTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/sdr/simulador': {
      id: '/app/configuracoes/sdr/simulador'
      path: '/configuracoes/sdr/simulador'
      fullPath: '/app/configuracoes/sdr/simulador'
      preLoaderRoute: typeof AppConfiguracoesSdrSimuladorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/sdr/orcamento': {
      id: '/app/configuracoes/sdr/orcamento'
      path: '/configuracoes/sdr/orcamento'
      fullPath: '/app/configuracoes/sdr/orcamento'
      preLoaderRoute: typeof AppConfiguracoesSdrOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/atendimento/tags': {
      id: '/app/configuracoes/atendimento/tags'
      path: '/configuracoes/atendimento/tags'
      fullPath: '/app/configuracoes/atendimento/tags'
      preLoaderRoute: typeof AppConfiguracoesAtendimentoTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/atendimento/pipeline': {
      id: '/app/configuracoes/atendimento/pipeline'
      path: '/configuracoes/atendimento/pipeline'
      fullPath: '/app/configuracoes/atendimento/pipeline'
      preLoaderRoute: typeof AppConfiguracoesAtendimentoPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/atendimento/motivos-perda': {
      id: '/app/configuracoes/atendimento/motivos-perda'
      path: '/configuracoes/atendimento/motivos-perda'
      fullPath: '/app/configuracoes/atendimento/motivos-perda'
      preLoaderRoute: typeof AppConfiguracoesAtendimentoMotivosPerdaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/atendimento/lifecycle': {
      id: '/app/configuracoes/atendimento/lifecycle'
      path: '/configuracoes/atendimento/lifecycle'
      fullPath: '/app/configuracoes/atendimento/lifecycle'
      preLoaderRoute: typeof AppConfiguracoesAtendimentoLifecycleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/atendimento/horario-comercial': {
      id: '/app/configuracoes/atendimento/horario-comercial'
      path: '/configuracoes/atendimento/horario-comercial'
      fullPath: '/app/configuracoes/atendimento/horario-comercial'
      preLoaderRoute: typeof AppConfiguracoesAtendimentoHorarioComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogo/$id/editar': {
      id: '/app/catalogo/$id/editar'
      path: '/editar'
      fullPath: '/app/catalogo/$id/editar'
      preLoaderRoute: typeof AppCatalogoIdEditarRouteImport
      parentRoute: typeof AppCatalogoIdRoute
    }
  }
}

interface AppAtendimentoRouteChildren {
  AppAtendimentoIdRoute: typeof AppAtendimentoIdRoute
  AppAtendimentoIndexRoute: typeof AppAtendimentoIndexRoute
}

const AppAtendimentoRouteChildren: AppAtendimentoRouteChildren = {
  AppAtendimentoIdRoute: AppAtendimentoIdRoute,
  AppAtendimentoIndexRoute: AppAtendimentoIndexRoute,
}

const AppAtendimentoRouteWithChildren = AppAtendimentoRoute._addFileChildren(
  AppAtendimentoRouteChildren,
)

interface AppCatalogoIdRouteChildren {
  AppCatalogoIdEditarRoute: typeof AppCatalogoIdEditarRoute
}

const AppCatalogoIdRouteChildren: AppCatalogoIdRouteChildren = {
  AppCatalogoIdEditarRoute: AppCatalogoIdEditarRoute,
}

const AppCatalogoIdRouteWithChildren = AppCatalogoIdRoute._addFileChildren(
  AppCatalogoIdRouteChildren,
)

interface AppCatalogoRouteChildren {
  AppCatalogoIdRoute: typeof AppCatalogoIdRouteWithChildren
  AppCatalogoNovoRoute: typeof AppCatalogoNovoRoute
  AppCatalogoIndexRoute: typeof AppCatalogoIndexRoute
}

const AppCatalogoRouteChildren: AppCatalogoRouteChildren = {
  AppCatalogoIdRoute: AppCatalogoIdRouteWithChildren,
  AppCatalogoNovoRoute: AppCatalogoNovoRoute,
  AppCatalogoIndexRoute: AppCatalogoIndexRoute,
}

const AppCatalogoRouteWithChildren = AppCatalogoRoute._addFileChildren(
  AppCatalogoRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppOrcamentosRouteChildren {
  AppOrcamentosIdRoute: typeof AppOrcamentosIdRoute
  AppOrcamentosNovoRoute: typeof AppOrcamentosNovoRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
}

const AppOrcamentosRouteChildren: AppOrcamentosRouteChildren = {
  AppOrcamentosIdRoute: AppOrcamentosIdRoute,
  AppOrcamentosNovoRoute: AppOrcamentosNovoRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
}

const AppOrcamentosRouteWithChildren = AppOrcamentosRoute._addFileChildren(
  AppOrcamentosRouteChildren,
)

interface AppVeiculosRouteChildren {
  AppVeiculosIdRoute: typeof AppVeiculosIdRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
}

const AppVeiculosRouteChildren: AppVeiculosRouteChildren = {
  AppVeiculosIdRoute: AppVeiculosIdRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
}

const AppVeiculosRouteWithChildren = AppVeiculosRoute._addFileChildren(
  AppVeiculosRouteChildren,
)

interface AppRouteChildren {
  AppAtendimentoRoute: typeof AppAtendimentoRouteWithChildren
  AppCarteiraRoute: typeof AppCarteiraRoute
  AppCatalogoRoute: typeof AppCatalogoRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppInicioRoute: typeof AppInicioRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppOrcamentosRoute: typeof AppOrcamentosRouteWithChildren
  AppPedidosRoute: typeof AppPedidosRoute
  AppSdrRoute: typeof AppSdrRoute
  AppVeiculosRoute: typeof AppVeiculosRouteWithChildren
  AppConfiguracoesAparenciaRoute: typeof AppConfiguracoesAparenciaRoute
  AppConfiguracoesAuditoriaRoute: typeof AppConfiguracoesAuditoriaRoute
  AppConfiguracoesDistribuicaoRoute: typeof AppConfiguracoesDistribuicaoRoute
  AppConfiguracoesDivisoesRoute: typeof AppConfiguracoesDivisoesRoute
  AppConfiguracoesGamificacaoRoute: typeof AppConfiguracoesGamificacaoRoute
  AppConfiguracoesLojasRoute: typeof AppConfiguracoesLojasRoute
  AppConfiguracoesPapeisRoute: typeof AppConfiguracoesPapeisRoute
  AppConfiguracoesPerfilRoute: typeof AppConfiguracoesPerfilRoute
  AppConfiguracoesPortalClienteRoute: typeof AppConfiguracoesPortalClienteRoute
  AppConfiguracoesUsuariosRoute: typeof AppConfiguracoesUsuariosRoute
  AppConfiguracoesWhatsappRoute: typeof AppConfiguracoesWhatsappRoute
  AppGestaoAbcRoute: typeof AppGestaoAbcRoute
  AppGestaoCaixaRoute: typeof AppGestaoCaixaRoute
  AppGestaoComissoesRoute: typeof AppGestaoComissoesRoute
  AppGestaoDespesasRoute: typeof AppGestaoDespesasRoute
  AppGestaoDreRoute: typeof AppGestaoDreRoute
  AppGestaoEstoqueRoute: typeof AppGestaoEstoqueRoute
  AppGestaoMetasRoute: typeof AppGestaoMetasRoute
  AppGestaoPositivacaoRoute: typeof AppGestaoPositivacaoRoute
  AppGestaoRankingRoute: typeof AppGestaoRankingRoute
  AppGestaoRentabilidadeRoute: typeof AppGestaoRentabilidadeRoute
  AppGestaoVendasRoute: typeof AppGestaoVendasRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppGestaoIndexRoute: typeof AppGestaoIndexRoute
  AppConfiguracoesAtendimentoHorarioComercialRoute: typeof AppConfiguracoesAtendimentoHorarioComercialRoute
  AppConfiguracoesAtendimentoLifecycleRoute: typeof AppConfiguracoesAtendimentoLifecycleRoute
  AppConfiguracoesAtendimentoMotivosPerdaRoute: typeof AppConfiguracoesAtendimentoMotivosPerdaRoute
  AppConfiguracoesAtendimentoPipelineRoute: typeof AppConfiguracoesAtendimentoPipelineRoute
  AppConfiguracoesAtendimentoTagsRoute: typeof AppConfiguracoesAtendimentoTagsRoute
  AppConfiguracoesSdrOrcamentoRoute: typeof AppConfiguracoesSdrOrcamentoRoute
  AppConfiguracoesSdrSimuladorRoute: typeof AppConfiguracoesSdrSimuladorRoute
  AppConfiguracoesSdrTemplatesRoute: typeof AppConfiguracoesSdrTemplatesRoute
  AppConfiguracoesVeiculosCadastroModeRoute: typeof AppConfiguracoesVeiculosCadastroModeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtendimentoRoute: AppAtendimentoRouteWithChildren,
  AppCarteiraRoute: AppCarteiraRoute,
  AppCatalogoRoute: AppCatalogoRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppInicioRoute: AppInicioRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppOrcamentosRoute: AppOrcamentosRouteWithChildren,
  AppPedidosRoute: AppPedidosRoute,
  AppSdrRoute: AppSdrRoute,
  AppVeiculosRoute: AppVeiculosRouteWithChildren,
  AppConfiguracoesAparenciaRoute: AppConfiguracoesAparenciaRoute,
  AppConfiguracoesAuditoriaRoute: AppConfiguracoesAuditoriaRoute,
  AppConfiguracoesDistribuicaoRoute: AppConfiguracoesDistribuicaoRoute,
  AppConfiguracoesDivisoesRoute: AppConfiguracoesDivisoesRoute,
  AppConfiguracoesGamificacaoRoute: AppConfiguracoesGamificacaoRoute,
  AppConfiguracoesLojasRoute: AppConfiguracoesLojasRoute,
  AppConfiguracoesPapeisRoute: AppConfiguracoesPapeisRoute,
  AppConfiguracoesPerfilRoute: AppConfiguracoesPerfilRoute,
  AppConfiguracoesPortalClienteRoute: AppConfiguracoesPortalClienteRoute,
  AppConfiguracoesUsuariosRoute: AppConfiguracoesUsuariosRoute,
  AppConfiguracoesWhatsappRoute: AppConfiguracoesWhatsappRoute,
  AppGestaoAbcRoute: AppGestaoAbcRoute,
  AppGestaoCaixaRoute: AppGestaoCaixaRoute,
  AppGestaoComissoesRoute: AppGestaoComissoesRoute,
  AppGestaoDespesasRoute: AppGestaoDespesasRoute,
  AppGestaoDreRoute: AppGestaoDreRoute,
  AppGestaoEstoqueRoute: AppGestaoEstoqueRoute,
  AppGestaoMetasRoute: AppGestaoMetasRoute,
  AppGestaoPositivacaoRoute: AppGestaoPositivacaoRoute,
  AppGestaoRankingRoute: AppGestaoRankingRoute,
  AppGestaoRentabilidadeRoute: AppGestaoRentabilidadeRoute,
  AppGestaoVendasRoute: AppGestaoVendasRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppGestaoIndexRoute: AppGestaoIndexRoute,
  AppConfiguracoesAtendimentoHorarioComercialRoute:
    AppConfiguracoesAtendimentoHorarioComercialRoute,
  AppConfiguracoesAtendimentoLifecycleRoute:
    AppConfiguracoesAtendimentoLifecycleRoute,
  AppConfiguracoesAtendimentoMotivosPerdaRoute:
    AppConfiguracoesAtendimentoMotivosPerdaRoute,
  AppConfiguracoesAtendimentoPipelineRoute:
    AppConfiguracoesAtendimentoPipelineRoute,
  AppConfiguracoesAtendimentoTagsRoute: AppConfiguracoesAtendimentoTagsRoute,
  AppConfiguracoesSdrOrcamentoRoute: AppConfiguracoesSdrOrcamentoRoute,
  AppConfiguracoesSdrSimuladorRoute: AppConfiguracoesSdrSimuladorRoute,
  AppConfiguracoesSdrTemplatesRoute: AppConfiguracoesSdrTemplatesRoute,
  AppConfiguracoesVeiculosCadastroModeRoute:
    AppConfiguracoesVeiculosCadastroModeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LojaContaRouteChildren {
  LojaContaPedidosRoute: typeof LojaContaPedidosRoute
}

const LojaContaRouteChildren: LojaContaRouteChildren = {
  LojaContaPedidosRoute: LojaContaPedidosRoute,
}

const LojaContaRouteWithChildren = LojaContaRoute._addFileChildren(
  LojaContaRouteChildren,
)

interface LojaRouteChildren {
  LojaBuscaRoute: typeof LojaBuscaRoute
  LojaCarrinhoRoute: typeof LojaCarrinhoRoute
  LojaCheckoutRoute: typeof LojaCheckoutRoute
  LojaContaRoute: typeof LojaContaRouteWithChildren
  LojaIndexRoute: typeof LojaIndexRoute
  LojaCategoriaSlugRoute: typeof LojaCategoriaSlugRoute
  LojaProdutoSlugRoute: typeof LojaProdutoSlugRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaBuscaRoute: LojaBuscaRoute,
  LojaCarrinhoRoute: LojaCarrinhoRoute,
  LojaCheckoutRoute: LojaCheckoutRoute,
  LojaContaRoute: LojaContaRouteWithChildren,
  LojaIndexRoute: LojaIndexRoute,
  LojaCategoriaSlugRoute: LojaCategoriaSlugRoute,
  LojaProdutoSlugRoute: LojaProdutoSlugRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  ErroRoute: ErroRoute,
  LojaRoute: LojaRouteWithChildren,
  PortalRoute: PortalRoute,
  SemPermissaoRoute: SemPermissaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
