import type { ID, ISO8601, Money } from "./common";

/**
 * Operational expense ledger (PRD-054).
 *
 * Replaces the three fixed mocked buckets used by the DRE (PRD-048) with real,
 * individual entries. Each expense carries **two dates** serving two accounting
 * regimes:
 *  - `competenceDate` (competência) → feeds the DRE (the month the expense
 *    refers to).
 *  - `paymentDate` (caixa) → feeds the Cash Flow (PRD-055) when the money
 *    actually left.
 *
 * @see ../../../docs/prds/PRD-054-despesas.md
 */

/**
 * Expense category. The nine categories aggregate into the three DRE operating
 * expense lines via {@link aggregateExpensesForDRE}:
 *  - `folha` → payroll
 *  - `aluguel` + `infraestrutura` → rentInfra
 *  - everything else → otherExpenses
 */
export type ExpenseCategory =
  | "folha"
  | "aluguel"
  | "infraestrutura"
  | "marketing"
  | "impostos"
  | "fornecedores"
  | "logistica"
  | "manutencao"
  | "outros";

/** Payment method used to settle an expense. */
export type ExpensePaymentMethod =
  | "pix"
  | "boleto"
  | "transferencia"
  | "dinheiro"
  | "cartao"
  | "debito_automatico";

/**
 * Status lifecycle of an expense.
 *  - `pendente`: created, not yet paid.
 *  - `pago`: settled (`paymentDate` set).
 *  - `atrasado`: past `dueDate` and still unpaid (set automatically by the
 *    daily timer).
 *  - `cancelado`: voided with confirmation.
 */
export type ExpenseStatus = "pendente" | "pago" | "atrasado" | "cancelado";

/** Recurrence frequency for a recurring expense series. */
export type ExpenseRecurrenceFrequency = "mensal" | "trimestral" | "anual";

/** Configuration of a recurring expense series (the "mother" record). */
export interface IExpenseRecurrence {
  frequency: ExpenseRecurrenceFrequency;
  /** Day of the month the expense is due (1-31). */
  dayOfMonth: number;
  /** Last competence the series recurs until; `undefined` = open-ended. */
  endDate?: ISO8601;
}

/**
 * Operational expense entry (PRD-054).
 *
 * Commissions are NOT modelled as expenses — they are computed by PRD-047 and
 * enter the DRE / Cash Flow through their own channel.
 */
export interface IExpense {
  id: ID;
  /** Human-readable description, e.g. "Conta de luz - janeiro/2026". */
  description: string;
  category: ExpenseCategory;
  amount: Money;

  // Dual temporality
  /** Month of competence (drives the DRE). */
  competenceDate: ISO8601;
  /** When the expense was actually paid (drives the Cash Flow); null = unpaid. */
  paymentDate?: ISO8601;

  // Status
  status: ExpenseStatus;
  /** Due date — drives the automatic transition to `atrasado`. */
  dueDate?: ISO8601;

  // Recurrence
  isRecurring: boolean;
  /** Set on "child" entries generated by a recurrence "mother". */
  recurrenceParentId?: ID;
  /** Present on the "mother" entry of a recurring series. */
  recurrenceConfig?: IExpenseRecurrence;

  // Details
  supplier?: string;
  paymentMethod?: ExpensePaymentMethod;
  /** Receipt attachment — placeholder for Fase 2 (Supabase Storage). */
  attachmentUrl?: string;
  notes?: string;

  // Multi-store + audit
  storeId: ID;
  createdBy: ID;
  createdAt: ISO8601;
  updatedAt: ISO8601;
}

/**
 * The three DRE operating-expense lines the nine categories aggregate into
 * (PRD-054 RF-023). Mirrors `IFinancialSettings.fixedExpenses` shape so the DRE
 * engine swap is drop-in.
 */
export interface IExpenseDREAggregate {
  payroll: Money;
  rentInfra: Money;
  otherExpenses: Money;
}

/** Map every {@link ExpenseCategory} to its DRE aggregate line. */
export const EXPENSE_CATEGORY_TO_DRE_LINE: Record<ExpenseCategory, keyof IExpenseDREAggregate> = {
  folha: "payroll",
  aluguel: "rentInfra",
  infraestrutura: "rentInfra",
  marketing: "otherExpenses",
  impostos: "otherExpenses",
  fornecedores: "otherExpenses",
  logistica: "otherExpenses",
  manutencao: "otherExpenses",
  outros: "otherExpenses",
};
