import type { Division, ID, ISO8601 } from "./common";
import type { PartCategory } from "./part-identification";
import type { GoalProgressStatus, GoalProgressTrend } from "./goals";

/** Metric an indicator tracks against the product slice. */
export type IndicatorMetric = "faturamento" | "quantidade" | "margem" | "pedidos";

/**
 * Scope level. `team` is intentionally omitted (dormant per briefing).
 * `global` = cross-store / chain level — live in MVP for owner dashboards.
 */
export type IndicatorScopeLevel = "store" | "individual" | "global";

/** Time granularity. */
export type IndicatorPeriodType = "diario" | "semanal" | "mensal" | "trimestral" | "anual";

/** Lifecycle status. */
export type IndicatorStatus = "ativo" | "concluido" | "arquivado" | "cancelado";

/**
 * Product slice the indicator measures. Discriminated by `kind`.
 * Subcategory is intentionally out of MVP — see issue #23.
 */
export type ProductSelector =
  | { kind: "category"; categories: PartCategory[] }
  | { kind: "sku"; partIds: ID[] }
  | { kind: "group"; label: string; categories?: PartCategory[]; partIds?: ID[] };

/** Time-bounded period of an indicator. */
export interface IIndicatorPeriod {
  type: IndicatorPeriodType;
  start: ISO8601;
  end: ISO8601;
}

/**
 * Product indicator — a target value for a metric, measured against a product
 * slice (category / sku / group), scoped by level and period.
 *
 * Separate concept from IGoal (PRD-042) — see
 * docs/superpowers/specs/2026-06-02-indicadores-por-produto-design.md
 */
export interface IProductIndicator {
  id: ID;
  storeId: ID;
  /** Human-readable name (autogenerated or customized). */
  name: string;
  selector: ProductSelector;
  metric: IndicatorMetric;
  scopeLevel: IndicatorScopeLevel;
  /** Present when `scopeLevel === "individual"`. */
  sellerId?: ID;
  period: IIndicatorPeriod;
  targetValue: number;
  status: IndicatorStatus;
  /** Restricts the indicator to a division when set (default parts in MVP). */
  division?: Division;
  /** Free-text reward shown to sellers. */
  rewardDescription?: string;
  /** Actor (Owner/Gestor) that created it. */
  createdBy: ID;
  /** Reason captured when status moves to `cancelado`. */
  cancelReason?: string;
  createdAt: ISO8601;
  updatedAt: ISO8601;
}

/** Per-seller contribution to a collective indicator. */
export interface IIndicatorContributor {
  sellerId: ID;
  /** Matched value attributed to this seller (BRL or count, depending on metric). */
  value: number;
  /** Fraction of `currentValue` (0..1). */
  share: number;
}

/**
 * Derived progress of an indicator — computed at runtime by
 * `calculateIndicatorProgress`. Never persisted.
 */
export interface IIndicatorProgress {
  indicatorId: ID;
  currentValue: number;
  /** Percentage of `targetValue` reached (0..200). */
  percentage: number;
  /** Linear projection of where the indicator will land if the pace holds. */
  projection: number;
  daysRemaining: number;
  totalDays: number;
  /** Traffic-light status (reuses the goals type). */
  status: GoalProgressStatus;
  trend: GoalProgressTrend;
  /** Pre-computed ratio `percentage / expectedAtDate`. */
  paceRatio: number;
  /** Seller breakdown, sorted desc by `value`. */
  contributors: IIndicatorContributor[];
}
