import type { IMetricDefinition } from "@/shared/types/analytics-copilot";

/** The only consultable vocabulary (RF-008). Each metric declares its source + executor. */
export const metricCatalog: IMetricDefinition[] = [
  {
    id: "faturamento",
    label: "Faturamento",
    description: "Receita total de pedidos pagos no período.",
    metricKey: "revenue",
    dimensions: ["marca", "categoria", "canal", "vendedor", "tempo"],
    supportedFilters: ["marca", "categoria", "canal", "vendedor"],
    keywords: ["faturamento", "faturei", "faturou", "vendi", "vendas", "receita", "faturado"],
    source: { prd: "PRD-041", panelRoute: "/app/gestao/vendas", label: "Vendas" },
    dataAccessKey: "getSalesMetric",
  },
  {
    id: "margem",
    label: "Margem",
    description: "Margem de contribuição (receita − custo) no período.",
    metricKey: "margin",
    dimensions: ["categoria", "cliente", "vendedor", "tempo"],
    supportedFilters: ["categoria", "vendedor"],
    keywords: ["margem", "lucro", "rentabilidade", "lucratividade"],
    source: { prd: "PRD-049", panelRoute: "/app/gestao/rentabilidade", label: "Rentabilidade" },
    dataAccessKey: "getMargin",
  },
  {
    id: "pedidos",
    label: "Pedidos",
    description: "Quantidade de pedidos pagos no período.",
    metricKey: "tickets",
    dimensions: ["vendedor", "canal", "tempo"],
    supportedFilters: ["vendedor", "canal"],
    keywords: ["pedidos", "quantos pedidos", "numero de pedidos", "tickets", "vendas fechadas"],
    source: { prd: "PRD-041", panelRoute: "/app/gestao/vendas", label: "Vendas" },
    dataAccessKey: "getSalesMetric",
  },
  {
    id: "ticket_medio",
    label: "Ticket médio",
    description: "Valor médio por pedido no período.",
    metricKey: "ticket_medio",
    dimensions: ["vendedor", "tempo"],
    supportedFilters: ["vendedor"],
    keywords: ["ticket medio", "valor medio", "media por pedido"],
    source: { prd: "PRD-041", panelRoute: "/app/gestao/vendas", label: "Vendas" },
    dataAccessKey: "getSalesMetric",
  },
  {
    id: "positivacao",
    label: "Positivação",
    description: "Clientes ativos que compraram ao menos uma vez no período.",
    metricKey: "positivacao",
    dimensions: ["vendedor", "tempo"],
    supportedFilters: ["vendedor"],
    keywords: ["positivacao", "clientes que compraram", "positivados"],
    source: { prd: "PRD-043", panelRoute: "/app/gestao/positivacao", label: "Positivação" },
    dataAccessKey: "getPositivation",
  },
  {
    id: "curva_abc",
    label: "Curva ABC",
    description: "Classificação de clientes por participação na receita (A/B/C).",
    metricKey: "abc",
    dimensions: ["cliente", "tempo"],
    supportedFilters: ["cliente"],
    keywords: ["curva abc", "classe a", "classe b", "classe c", "melhores clientes"],
    source: { prd: "PRD-045", panelRoute: "/app/gestao/abc", label: "Curva ABC" },
    dataAccessKey: "getABCClass",
  },
  {
    id: "carteira",
    label: "Carteira",
    description: "Status da carteira de clientes (ativo, dormente, perdido, recuperação).",
    metricKey: "carteira",
    dimensions: ["vendedor", "cliente"],
    supportedFilters: ["vendedor"],
    keywords: ["carteira", "clientes em risco", "clientes dormentes", "churn", "clientes perdidos"],
    source: { prd: "PRD-046", panelRoute: "/app/gestao/carteira-analitica", label: "Carteira" },
    dataAccessKey: "getPortfolioStatus",
  },
  {
    id: "forecast",
    label: "Forecast de fechamento",
    description: "Projeção de fechamento do período (cenário provável).",
    metricKey: "forecast",
    dimensions: ["loja", "vendedor", "tempo"],
    supportedFilters: ["vendedor"],
    keywords: ["forecast", "projecao", "vou fechar", "previsao de fechamento", "onde vou fechar"],
    source: { prd: "PRD-056", panelRoute: "/app/gestao/forecast", label: "Forecast" },
    dataAccessKey: "getForecast",
  },
];

export function findMetricById(id: string): IMetricDefinition | undefined {
  return metricCatalog.find((m) => m.id === id);
}
